import type { Recommendation } from '../../types/economic'
import { Badge, useCopy } from '../DataDisplay'

const stages=[
  {key:'immediate',fr:'Immédiat',ar:'فوري',periodFr:'0–3 mois',periodAr:'0–3 أشهر'},
  {key:'stabilization',fr:'Stabilisation',ar:'استقرار',periodFr:'3–12 mois',periodAr:'3–12 شهراً'},
  {key:'recovery',fr:'Reprise',ar:'تعافٍ',periodFr:'1–3 ans',periodAr:'1–3 سنوات'},
  {key:'structural',fr:'Résilience structurelle',ar:'مرونة هيكلية',periodFr:'Plus de 3 ans',periodAr:'أكثر من 3 سنوات'},
] as const

export function ResponseTimeline({recommendations}:{recommendations:Recommendation[]}) {
  const c=useCopy()
  return <div data-testid="recommendation-timeline" className="relative grid gap-5 lg:grid-cols-4 before:absolute before:start-5 before:top-5 before:hidden before:h-1 before:w-[calc(100%-2.5rem)] before:bg-gradient-to-r before:from-orange-300 before:via-gold-300 before:to-mauritania-500 lg:before:block">{stages.map((stage,index)=>{const items=recommendations.filter(item=>item.time_horizon===stage.key);return <section className="relative z-10" key={stage.key}><div className="mb-4 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-navy-900 font-black text-white ring-4 ring-white">{index+1}</span><div><h3 className="font-black text-navy-950">{c(stage.fr,stage.ar)}</h3><p className="text-xs text-slate-500">{c(stage.periodFr,stage.periodAr)}</p></div></div><div className="grid gap-3">{items.map(item=><article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm" key={item.code}><div className="flex items-start justify-between gap-2"><h4 className="font-bold text-navy-950">{c(item.title_fr,item.title_ar)}</h4><Badge tone={item.priority==='critical'?'danger':item.priority==='high'?'warning':'neutral'}>{item.priority}</Badge></div><p className="mt-3 text-sm leading-6 text-slate-700">{c(item.reason_fr,item.reason_ar)}</p><p className="mt-3 text-sm"><strong>{c('Objectif : ','الهدف: ')}</strong>{c(item.expected_objective_fr,item.expected_objective_ar)}</p><p className="mt-3 text-xs text-slate-500"><strong>{c('À suivre : ','للمتابعة: ')}</strong>{item.monitoring_indicators.join(', ')}</p><div className="mt-3"><Badge>{c('Confiance','الثقة')}: {item.confidence}</Badge></div><details className="mt-3 rounded-xl bg-slate-50 p-3 text-xs"><summary className="cursor-pointer font-bold text-mauritania-800">{c('Pourquoi cette recommandation ?','لماذا هذه التوصية؟')}</summary><p className="mt-2 leading-5">{item.supporting_metrics.length?item.supporting_metrics.join(' · '):c('Fondée sur le choc et l’historique sectoriel disponibles.','مبنية على الصدمة والتاريخ القطاعي المتاح.')}</p><p className="mt-2 text-slate-500">{c(item.limitations_fr,item.limitations_ar)}</p></details></article>)}{!items.length&&<p className="rounded-xl bg-slate-50 p-3 text-xs text-slate-500">{c('Aucune action requise à ce stade.','لا يلزم إجراء في هذه المرحلة.')}</p>}</div></section>})}</div>
}
