import {useMemo,useState} from 'react'
import {Area,AreaChart,CartesianGrid,Cell,Legend,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import type {Point} from '../../types/economic'
import {useLanguage} from '../../contexts/LanguageContext'
import {useCopy} from '../DataDisplay'
export type NamedSeries={code:string;fr:string;ar:string;color:string;points:Point[]}
function merge(series:NamedSeries[]){const rows=new Map<number,Record<string,number|string|null>>();for(const item of series)for(const point of item.points){const row=rows.get(point.year)??{year:point.year};row[item.code]=point.value;rows.set(point.year,row)}return [...rows.values()].sort((a,b)=>Number(a.year)-Number(b.year))}
export function GdpStructureAreaChart({series}:{series:NamedSeries[]}){const c=useCopy();return <div data-testid="gdp-structure-chart" className="h-[360px] w-full"><ResponsiveContainer><AreaChart data={merge(series)}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="year"/><YAxis width={70}/><Tooltip/><Legend/>{series.map(item=><Area key={item.code} type="monotone" stackId="gdp" dataKey={item.code} name={c(item.fr,item.ar)} stroke={item.color} fill={item.color} connectNulls={false}/>)}</AreaChart></ResponsiveContainer></div>}
export function SectorEvolutionChart({series}:{series:NamedSeries[]}){const c=useCopy();const [hidden,setHidden]=useState<Set<string>>(new Set());return <div><div className="mb-3 flex flex-wrap gap-2">{series.map(item=><button type="button" key={item.code} onClick={()=>setHidden(old=>{const next=new Set(old);if(next.has(item.code))next.delete(item.code);else next.add(item.code);return next})} className={`min-h-10 rounded-full px-3 text-xs font-bold ring-1 ${hidden.has(item.code)?'bg-slate-100 text-slate-400 ring-slate-200':'bg-white ring-slate-300'}`}><span className="me-2 inline-block h-2.5 w-2.5 rounded-full" style={{background:item.color}}/>{c(item.fr,item.ar)}</button>)}</div><div data-testid="sector-evolution-chart" className="h-[380px]"><ResponsiveContainer><LineChart data={merge(series)}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="year"/><YAxis width={70}/><Tooltip/><Legend/>{series.filter(item=>!hidden.has(item.code)).map(item=><Line key={item.code} type="monotone" dataKey={item.code} name={c(item.fr,item.ar)} stroke={item.color} strokeWidth={2.5} dot={false} connectNulls={false}/>)}</LineChart></ResponsiveContainer></div></div>}
export function GdpMiningDependenceChart({gdp,mining}:{gdp:Point[];mining:Point[]}){const c=useCopy();const map=new Map(mining.map(point=>[point.year,point.value]));const data=gdp.map(point=>({year:point.year,gdp:point.value,withoutMining:point.value==null||map.get(point.year)==null?null:point.value-(map.get(point.year) as number)}));return <div data-testid="gdp-without-mining-chart" className="h-[340px]"><ResponsiveContainer><LineChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="year"/><YAxis width={70}/><Tooltip/><Legend/><Line type="monotone" dataKey="gdp" name={c('PIB total','\u0625\u062c\u0645\u0627\u0644\u064a \u0627\u0644\u0646\u0627\u062a\u062c')} stroke="#183149" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="withoutMining" name={c('PIB hors extraction','\u0627\u0644\u0646\u0627\u062a\u062c \u062f\u0648\u0646 \u0627\u0644\u0627\u0633\u062a\u062e\u0631\u0627\u062c')} stroke="#16865c" strokeWidth={2.5} dot={false} connectNulls={false}/></LineChart></ResponsiveContainer></div>}
export function SectorShareDonut({items}:{items:Array<{fr:string;ar:string;value:number|null;color:string}>}){const c=useCopy();const data=items.filter((item):item is typeof item&{value:number}=>item.value!=null).map(item=>({name:c(item.fr,item.ar),value:item.value,color:item.color}));return <div data-testid="sector-share-donut" className="h-[330px]"><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius="52%" outerRadius="82%" paddingAngle={2}>{data.map(item=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></div>}
export function SectorGrowthHeatmap({series}:{series:NamedSeries[]}){const c=useCopy();const {language}=useLanguage();const years=useMemo(()=>[...new Set(series.flatMap(item=>item.points.map(point=>point.year)))].sort((a,b)=>a-b).slice(-12),[series]);const growth=(points:Point[],year:number)=>{const current=points.find(p=>p.year===year)?.value,previous=points.find(p=>p.year===year-1)?.value;return current==null||previous==null||previous===0?null:(current-previous)/Math.abs(previous)*100};const color=(value:number|null)=>value==null?'#94a3b8':value>0?`rgba(22,134,92,${Math.min(.95,.25+Math.abs(value)/40)})`:`rgba(210,55,55,${Math.min(.95,.25+Math.abs(value)/40)})`;return <div data-testid="sector-growth-heatmap" className="overflow-x-auto"><table className="min-w-[850px] border-separate border-spacing-1 text-xs"><thead><tr><th className="p-2 text-start">{c('Secteur','\u0627\u0644\u0642\u0637\u0627\u0639')}</th>{years.map(year=><th key={year} className="p-2">{year}</th>)}</tr></thead><tbody>{series.map(item=><tr key={item.code}><th className="whitespace-nowrap p-2 text-start">{c(item.fr,item.ar)}</th>{years.map(year=>{const value=growth(item.points,year);return <td key={year} title={value==null?c('Non disponible','\u063a\u064a\u0631 \u0645\u062a\u0627\u062d'):`${new Intl.NumberFormat(language==='ar'?'ar-MR':'fr-MR',{maximumFractionDigits:1}).format(value)}%`} className="h-10 min-w-14 rounded text-center font-bold text-white" style={{backgroundColor:color(value)}}>{value==null?'\u2014':`${value>0?'+':''}${value.toFixed(1)}`}</td>})}</tr>)}</tbody></table></div>}
