import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useCopy } from '../DataDisplay'
import { EconomicTooltip } from './EconomicTooltip'

export function GdpScenarioComparisonChart({unaffectedEconomyValue,affectedSectorValue,remainingAffectedValue,directLoss,targetExistingValue,compensationGain}:{unaffectedEconomyValue:number;affectedSectorValue:number;remainingAffectedValue:number;directLoss:number;targetExistingValue:number;compensationGain:number}){
 const c=useCopy();const unaffectedExcludingTargets=Math.max(0,unaffectedEconomyValue-targetExistingValue);const data=[
  {name:c('Avant le choc','قبل الصدمة'),unaffected:unaffectedExcludingTargets,affected:affectedSectorValue,target:targetExistingValue,loss:0,gain:0},
  {name:c('Après le choc','بعد الصدمة'),unaffected:unaffectedExcludingTargets,affected:remainingAffectedValue,target:targetExistingValue,loss:directLoss,gain:0},
  {name:c('Après compensation','بعد التعويض'),unaffected:unaffectedExcludingTargets,affected:remainingAffectedValue,target:targetExistingValue,loss:0,gain:compensationGain},
 ];const labels:Record<string,string>={unaffected:c('Économie non affectée hors cibles','الاقتصاد غير المتأثر باستثناء القطاعات المستهدفة'),affected:c('Secteur affecté','القطاع المتأثر'),target:c('Valeur existante des cibles','القيمة الحالية للقطاعات المستهدفة'),loss:c('Perte directe','الخسارة المباشرة'),gain:c('Hausse comptable requise','الزيادة المحاسبية المطلوبة')}
 return <div data-testid="gdp-scenario-comparison-chart" className="h-[360px] w-full max-w-full overflow-hidden" role="img" aria-label={c('PIB avant, après le choc et après compensation comptable','الناتج قبل الصدمة وبعدها وبعد التعويض المحاسبي')}><ResponsiveContainer><BarChart data={data} margin={{top:12,right:4,left:0,bottom:12}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis width={68}/><Tooltip content={({active,label,payload})=><EconomicTooltip active={active} year={String(label??'')} items={(payload??[]).map(item=>({name:labels[String(item.dataKey)]??String(item.name),value:item.value==null?null:Number(item.value),unit:c('millions MRU','مليون أوقية'),status:String(label)===c('Avant le choc','قبل الصدمة')?'observed':'simulated'}))}/>} /><Legend/><Bar dataKey="unaffected" name={labels.unaffected} stackId="gdp" fill="#1d3557"/><Bar dataKey="affected" name={labels.affected} stackId="gdp" fill="#e9852d"/><Bar dataKey="target" name={labels.target} stackId="gdp" fill="#16865c"/><Bar dataKey="loss" name={labels.loss} stackId="gdp" fill="#e85d3f" fillOpacity={0.45}/><Bar dataKey="gain" name={labels.gain} stackId="gdp" fill="#3aa876"/></BarChart></ResponsiveContainer></div>
}
