import { useState } from 'react'
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { Point } from '../../types/economic'
import { useCopy } from '../DataDisplay'

export type MultiSeries={code:string;name:string;unit:string;points:Point[]}
const colors=['#087f5b','#e67700','#1c4e80','#c92a2a','#7048e8','#0b7285'];const dashes=['0','0','0','6 3','3 3','8 3 2 3']
export function MultiIndicatorChart({series,smallMultiples=false}:{series:MultiSeries[];smallMultiples?:boolean}){const c=useCopy();const [hidden,setHidden]=useState<string[]>([]);const years=[...new Set(series.flatMap(s=>s.points.map(p=>p.year)))].sort();const data=years.map(year=>Object.fromEntries([['year',year],...series.map(s=>[s.code,s.points.find(p=>p.year===year)?.value??null])]))
 if(smallMultiples)return <div data-testid="small-multiples" className="grid gap-4 md:grid-cols-2">{series.map((s,i)=>{const valid=s.points.filter(p=>p.value!=null),latest=valid.at(-1),previous=valid.at(-2),growth=latest?.value!=null&&previous?.value!=null&&previous.value!==0?(latest.value-previous.value)/Math.abs(previous.value)*100:null;return <div className="rounded-xl border p-3" key={s.code}><h3 className="font-bold">{s.name}</h3><p className="text-xs text-slate-500">{s.unit} · {c('Dernière valeur','آخر قيمة')}: {latest?.value?.toLocaleString()??'—'} · {c('Croissance','النمو')}: {growth==null?'—':`${growth.toFixed(2)}%`}</p><div className="h-44"><ResponsiveContainer><LineChart data={s.points}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="year" tick={{fontSize:10}}/><YAxis width={55} tick={{fontSize:10}}/><Tooltip/><Line dataKey="value" name={s.name} stroke={colors[i]} connectNulls={false} dot={false}/></LineChart></ResponsiveContainer></div></div>})}</div>
 return <div data-testid="multi-indicator-chart" className="w-full" role="img" aria-label={c('Comparaison de plusieurs indicateurs','مقارنة مؤشرات متعددة')}><div className="h-[380px]"><ResponsiveContainer><LineChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="year"/><YAxis width={70}/><Tooltip contentStyle={{borderRadius:12}}/><Legend/>{series.map((s,i)=><Line key={s.code} dataKey={s.code} name={s.name} stroke={colors[i]} strokeDasharray={dashes[i]} strokeWidth={2.5} dot={series.length>4?{r:2}:false} hide={hidden.includes(s.code)} connectNulls={false}/>)}</LineChart></ResponsiveContainer></div><div className="flex flex-wrap justify-center gap-2">{series.map((s,i)=><button type="button" aria-pressed={!hidden.includes(s.code)} onClick={()=>setHidden(x=>x.includes(s.code)?x.filter(v=>v!==s.code):[...x,s.code])} className="rounded-full border px-3 py-1 text-xs font-bold" style={{color:colors[i]}} key={s.code}>{s.name}</button>)}</div></div>}
