import { calculateLatestYearScenario, detectLatestAvailableYear, latestValue } from '../utils/latestYearSimulation'

const input={baseGdp:1200,primarySector:300,secondarySector:400,tertiarySector:400,miningValues:{snim_iron:100,gold_copper:50,oil_gas_extraction:20},miningRates:{snim_iron:-.5,gold_copper:0,oil_gas_extraction:0},diversificationValues:{agriculture_fishing:150,manufacturing:200,services_commerce:250},diversificationRates:{agriculture_fishing:0,manufacturing:.1,services_commerce:0}}
describe('latest-year simulation calculations',()=>{
 it('detects the most recent non-missing GDP observation',()=>{const series=[{year:2023,value:10},{year:2024,value:null},{year:2022,value:9}];expect(detectLatestAvailableYear(series)).toBe(2023);expect(latestValue(series,2024)).toBeNull()})
 it('combines mining changes and diversification gains without rounding inputs',()=>{const result=calculateLatestYearScenario(input);expect(result.totalMiningLosses).toBe(50);expect(result.totalDiversificationGains).toBe(20);expect(result.netImpact).toBe(-30);expect(result.scenarioGdp).toBe(1170);expect(result.variationPercent).toBeCloseTo(-2.5);expect(result.categories.find(item=>item.key==='secondary')?.scenario).toBe(370)})
 it('does not fabricate a minerals total when an observation is missing',()=>{const result=calculateLatestYearScenario({...input,miningValues:{...input.miningValues,oil_gas_extraction:null},miningRates:{...input.miningRates,oil_gas_extraction:0}});expect(result.categories.find(item=>item.key==='minerals')).toEqual({key:'minerals',base:null,scenario:null});expect(result.warnings).toContain('missing:oil_gas_extraction')})
 it('rejects rates outside the documented slider bounds',()=>{expect(()=>calculateLatestYearScenario({...input,miningRates:{...input.miningRates,snim_iron:-.81}})).toThrow(RangeError);expect(()=>calculateLatestYearScenario({...input,diversificationRates:{...input.diversificationRates,manufacturing:.51}})).toThrow(RangeError)})
})
