import { fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { LanguageProvider } from '../contexts/LanguageContext'
import { SimulationAndReactionPage } from '../pages/SimulationAndReactionPage'
import * as stress from '../services/stressTest'
import * as recommendations from '../services/recommendations'
import i18n from '../i18n'
import { MemoryRouter, useNavigate } from 'react-router-dom'
vi.mock('../services/stressTest');vi.mock('../services/recommendations')
const base={category:'sector',hierarchy_level:1,unit:'Millions de MRU',source_side:'activity',is_aggregate:false,is_alias:false}
const sectors=[{...base,id:1,code:'primary_sector',name_fr:'Secteur primaire',name_ar:'القطاع الأولي'},{...base,id:2,code:'extractive_activities',name_fr:'Activités extractives',name_ar:'الأنشطة الاستخراجية'},{...base,id:3,code:'fishing',name_fr:'Pêche',name_ar:'الصيد'},{...base,id:4,code:'manufacturing',name_fr:'Industrie',name_ar:'الصناعة'},{...base,id:5,code:'construction_public_works',name_fr:'BTP',name_ar:'البناء'},{...base,id:6,code:'tertiary_sector',name_fr:'Tertiaire',name_ar:'الثالثي'},{...base,id:7,code:'secondary_sector',name_fr:'Secteur secondaire',name_ar:'القطاع الثانوي'}]
const points=(a:number,b:number)=>[{year:2023,value:a},{year:2024,value:b}];const composition=[2023,2024].map(year=>({year,gdp:400,primary_sector:80,extractive_activities:80,manufacturing:40,construction_public_works:20,tertiary_sector:180}));const pageData={sectors,years:[2023,2024],composition,gdpSeries:points(380,400),seriesByCode:{primary_sector:points(70,80),extractive_activities:points(70,80),fishing:points(20,40),manufacturing:points(35,40),construction_public_works:points(18,20),tertiary_sector:points(170,180),secondary_sector:points(123,140)}}
function setup(){vi.mocked(stress.loadSimulationPageData).mockResolvedValue(pageData);vi.mocked(recommendations.generateRecommendations).mockRejectedValue(new Error('not requested'))}function renderPage(path='/simulate'){return render(<LanguageProvider><MemoryRouter initialEntries={[path]}><SimulationAndReactionPage/></MemoryRouter></LanguageProvider>)}
function HistoryControls(){const navigate=useNavigate();return <><button onClick={()=>navigate(-1)}>Back test</button><button onClick={()=>navigate(1)}>Forward test</button></>}
describe('reactive scenario cockpit',()=>{beforeEach(()=>{vi.clearAllMocks();setup()})
 it('loads initial data once and renders all coordinated charts in French LTR',async()=>{renderPage();expect(await screen.findByRole('heading',{name:'Et si un secteur s’arrêtait demain ?'})).toBeInTheDocument();expect(document.documentElement).toHaveAttribute('dir','ltr');expect(stress.loadSimulationPageData).toHaveBeenCalledTimes(1);expect(screen.getByTestId('waterfall-chart')).toBeInTheDocument();expect(screen.getByTestId('gdp-scenario-comparison-chart')).toBeInTheDocument();expect(screen.getByTestId('compensation-sector-chart')).toBeInTheDocument();expect(screen.getByTestId('composition-chart')).toBeInTheDocument();expect(screen.getAllByText(/exigence comptable extrême/).length).toBeGreaterThan(0);expect(screen.getByText('Classement expérimental des secteurs de résilience')).toBeInTheDocument()})
 it('calculates loss, simulated GDP and impact locally without slider API calls',async()=>{renderPage();await screen.findByTestId('shock-slider');const result=screen.getByText('Impact direct dominant').parentElement!;expect(result).toHaveTextContent('10%');expect(result).toHaveTextContent('40');expect(result).toHaveTextContent('360');fireEvent.change(screen.getByTestId('shock-slider'),{target:{value:'75'}});expect(result).toHaveTextContent('15%');expect(stress.simulateSingle).not.toHaveBeenCalled();expect(stress.loadImpactPreview).not.toHaveBeenCalled()})
 it('updates year and sector from cached series',async()=>{const user=userEvent.setup();renderPage();await screen.findByTestId('simulation-year');await user.selectOptions(screen.getByTestId('simulation-year'),'2023');await user.selectOptions(screen.getByTestId('simulation-sector'),'fishing');expect(screen.getByText('Impact direct dominant').parentElement).toHaveTextContent(/2[,.]63%/);expect(stress.loadSimulationPageData).toHaveBeenCalledTimes(1)})
 it('supports quick controls and the slider Home and End keys',async()=>{const user=userEvent.setup();renderPage();const slider=await screen.findByTestId('shock-slider');for(const value of [10,25,50,75,100]){await user.click(screen.getByRole('button',{name:`${value}%`}));expect(slider).toHaveValue(String(value))}fireEvent.keyDown(slider,{key:'Home'});expect(slider).toHaveValue('0');fireEvent.keyDown(slider,{key:'End'});expect(slider).toHaveValue('100');expect(stress.simulateSingle).not.toHaveBeenCalled()})
 it('selects a sector from the historical chart controls',async()=>{const user=userEvent.setup();renderPage();await screen.findByTestId('simulation-sector');await user.click(screen.getByTestId('composition-select-primary_sector'));expect(screen.getByTestId('simulation-sector')).toHaveValue('primary_sector')})
 it('selects multiple target sectors and prevents affected and hierarchy reuse',async()=>{const user=userEvent.setup();renderPage();const search=await screen.findByLabelText('Rechercher un secteur cible');await user.type(search,'Industrie');await user.click(within(screen.getByRole('listbox')).getByRole('option',{name:'Industrie'}));expect(screen.getByText(/2\/4 secteurs/)).toBeInTheDocument();await user.clear(search);await user.type(search,'Activités extractives');await user.click(within(screen.getByRole('listbox')).getByRole('option',{name:'Activités extractives'}));expect(screen.getByRole('alert')).toHaveTextContent('ne peut pas se compenser');await user.clear(search);await user.type(search,'Pêche');await user.click(within(screen.getByRole('listbox')).getByRole('option',{name:'Pêche'}));await user.clear(search);await user.type(search,'Secteur primaire');await user.click(within(screen.getByRole('listbox')).getByRole('option',{name:'Secteur primaire'}));expect(screen.getByRole('alert')).toHaveTextContent('double comptage')})
 it('validates shared compensation allocation totals',async()=>{const user=userEvent.setup();renderPage();const search=await screen.findByLabelText('Rechercher un secteur cible');await user.type(search,'Industrie');await user.click(within(screen.getByRole('listbox')).getByRole('option',{name:'Industrie'}));await user.click(screen.getByRole('radio',{name:'Compensation partagée'}));const btp=screen.getByLabelText('Allocation de BTP'),industry=screen.getByLabelText('Allocation de Industrie');await user.clear(btp);await user.type(btp,'70');expect(screen.getByText(/doit être égal à 100%/)).toBeInTheDocument();await user.clear(industry);await user.type(industry,'30');expect(screen.getByText(/100% ✓/)).toBeInTheDocument()})
 it('restores a shared multi-target simulation URL without requesting a preview',async()=>{renderPage('/simulate?year=2023&affected=fishing&shock=75&targets=construction_public_works,manufacturing');expect(await screen.findByTestId('simulation-year')).toHaveValue('2023');expect(screen.getByTestId('simulation-sector')).toHaveValue('fishing');expect(screen.getByTestId('shock-slider')).toHaveValue('75');expect(screen.getByText(/2\/4 secteurs/)).toBeInTheDocument();expect(stress.simulateSingle).not.toHaveBeenCalled()})
 it('restores Back and Forward state and replaces slider history entries',async()=>{const user=userEvent.setup();render(<LanguageProvider><MemoryRouter initialEntries={['/simulate?year=2023&sector=fishing&shock=10','/simulate?year=2024&sector=extractive_activities&shock=50']} initialIndex={1}><HistoryControls/><SimulationAndReactionPage/></MemoryRouter></LanguageProvider>);const slider=await screen.findByTestId('shock-slider');fireEvent.change(slider,{target:{value:'75'}});fireEvent.change(slider,{target:{value:'90'}});await user.click(screen.getByText('Back test'));expect(slider).toHaveValue('10');expect(screen.getByTestId('simulation-sector')).toHaveValue('fishing');await user.click(screen.getByText('Forward test'));expect(slider).toHaveValue('90')})
 it('supports Arabic RTL',async()=>{await i18n.changeLanguage('ar');renderPage();expect(await screen.findByRole('heading',{name:'ماذا لو توقف أحد القطاعات غداً؟'})).toBeInTheDocument();expect(document.documentElement).toHaveAttribute('dir','rtl')})
 it('keeps the impact before the waterfall in the mobile visual order',async()=>{Object.defineProperty(window,'innerWidth',{value:320,writable:true,configurable:true});renderPage();const grid=await screen.findByTestId('cockpit-grid');expect(grid.children[0]).toHaveClass('order-1');expect(grid.children[1]).toHaveClass('order-3');expect(grid.children[2]).toHaveClass('order-2');expect(grid.closest('main')).toHaveClass('overflow-x-clip')})
 it('shows missing-data and initial backend-unavailable states',async()=>{vi.mocked(stress.loadSimulationPageData).mockResolvedValue({...pageData,seriesByCode:{...pageData.seriesByCode,extractive_activities:[{year:2024,value:null}]}});const first=renderPage();expect(await screen.findAllByText('Valeur manquante')).not.toHaveLength(0);first.unmount();vi.mocked(stress.loadSimulationPageData).mockRejectedValue(new Error('network unavailable'));renderPage();expect(await screen.findByText('Impossible de charger ces données')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Réessayer'})).toBeInTheDocument()})
})
