import { accountingFeasibility, calculateRequiredCompensationGrowth, calculateSectorShock, calculateSharedCompensation, calculateSingleSectorShock, hasHierarchyOverlap, historicalEvidence, resilienceRanking, targetConflict } from '../utils/simulation'

it('calculates the documented direct sector shock',()=>{const result=calculateSectorShock({baselineGdp:1000,affectedSectorValue:200,shockRate:.5});expect(result).toMatchObject({directLoss:100,simulatedGdp:900,directImpactPercentage:10,affectedSectorRemainingValue:100,unaffectedEconomyValue:800})})
it('keeps the previous single-sector function compatible',()=>{const result=calculateSingleSectorShock({baselineGdp:400,sectorValue:80,shockRate:.5});expect(result).toMatchObject({directLoss:40,simulatedGdp:360,directImpactPercentage:10,remainingSectorValue:40,unaffectedGdp:320})})
it('calculates target-sector compensation growth',()=>{expect(calculateRequiredCompensationGrowth({directLoss:100,targetSectorValue:250})).toMatchObject({requiredAdditionalValue:100,requiredGrowthPercentage:40,targetValueAfterCompensation:350,status:'calculated'})})
it('calculates shared compensation only when allocations total 100%',()=>{const rows=calculateSharedCompensation(100,[{code:'construction',share:60,targetSectorValue:200},{code:'commerce',share:40,targetSectorValue:400}]);expect(rows[0]).toMatchObject({allocatedLoss:60,requiredGrowthPercentage:30});expect(rows[1]).toMatchObject({allocatedLoss:40,requiredGrowthPercentage:10});expect(()=>calculateSharedCompensation(100,[{code:'construction',share:70,targetSectorValue:200}])).toThrow('100%')})
it('rejects invalid, missing, zero and non-finite inputs without zero filling',()=>{expect(()=>calculateSingleSectorShock({baselineGdp:0,sectorValue:1,shockRate:.5})).toThrow();expect(()=>calculateSingleSectorShock({baselineGdp:100,sectorValue:null,shockRate:.5})).toThrow();expect(()=>calculateRequiredCompensationGrowth({directLoss:10,targetSectorValue:null})).toThrow();expect(()=>calculateRequiredCompensationGrowth({directLoss:10,targetSectorValue:0})).toThrow()})
it('detects affected-sector reuse and parent-child double counting',()=>{expect(hasHierarchyOverlap('secondary_sector','construction_public_works')).toBe(true);expect(targetConflict('extractive_activities',[],'extractive_activities')).toBe('affected-overlap');expect(targetConflict('fishing',['secondary_sector'],'construction_public_works')).toBe('target-overlap');expect(targetConflict('fishing',['commerce'],'construction_public_works')).toBeNull()})
it('derives chronological historical evidence without converting NA to zero',()=>{const evidence=historicalEvidence([{year:2020,value:100},{year:2021,value:null},{year:2022,value:120},{year:2023,value:150}]);expect(evidence.growthCount).toBe(1);expect(evidence.latestGrowth).toBe(25);expect(evidence.completeness).toBe(75)})
it('classifies experimental accounting feasibility thresholds',()=>{expect([9,10,25,50,100].map(accountingFeasibility)).toEqual(['attainable','demanding','highly-demanding','very-difficult','extreme'])})
it('ranks compatible sectors with documented evidence and suppresses conflicts',()=>{const points=[{year:2020,value:100},{year:2021,value:110},{year:2022,value:121}];const ranking=resilienceRanking([{code:'commerce',sectorValue:200,baselineGdp:1000,directLoss:100,points,hierarchyConflict:false},{code:'secondary_sector',sectorValue:400,baselineGdp:1000,directLoss:100,points,hierarchyConflict:true}]);expect(ranking.find(row=>row.code==='commerce')).toMatchObject({requiredGrowth:50,averageGrowth:10,completeness:100,confidence:'low'});expect(ranking.find(row=>row.code==='secondary_sector')?.score).toBe(0)})
