import { fireEvent, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { LanguageProvider } from '../contexts/LanguageContext'
import { SimulationAndReactionPage } from '../pages/SimulationAndReactionPage'
import * as stress from '../services/stressTest'
import * as recommendations from '../services/recommendations'
import i18n from '../i18n'
vi.mock('../services/stressTest');vi.mock('../services/recommendations')
const base={category:'sector',hierarchy_level:1,unit:'Millions de MRU',source_side:'activity',is_aggregate:false,is_alias:false}
const sectors=[{...base,id:1,code:'primary_sector',name_fr:'Secteur primaire',name_ar:'القطاع الأولي'},{...base,id:2,code:'extractive_activities',name_fr:'Activités extractives',name_ar:'الأنشطة الاستخراجية'},{...base,id:3,code:'fishing',name_fr:'Pêche',name_ar:'الصيد'},{...base,id:4,code:'manufacturing',name_fr:'Industrie',name_ar:'الصناعة'},{...base,id:5,code:'construction_public_works',name_fr:'BTP',name_ar:'البناء'},{...base,id:6,code:'tertiary_sector',name_fr:'Tertiaire',name_ar:'الثالثي'}]
const points=(a:number,b:number)=>[{year:2023,value:a},{year:2024,value:b}];const composition=[2023,2024].map(year=>({year,gdp:400,primary_sector:80,extractive_activities:80,manufacturing:40,construction_public_works:20,tertiary_sector:180}));const pageData={sectors,years:[2023,2024],composition,gdpSeries:points(380,400),seriesByCode:{primary_sector:points(70,80),extractive_activities:points(70,80),fishing:points(20,40),manufacturing:points(35,40),construction_public_works:points(18,20),tertiary_sector:points(170,180)}}
function setup(){vi.mocked(stress.loadSimulationPageData).mockResolvedValue(pageData);vi.mocked(recommendations.generateRecommendations).mockRejectedValue(new Error('not requested'))}function renderPage(){return render(<LanguageProvider><SimulationAndReactionPage/></LanguageProvider>)}
describe('reactive scenario cockpit',()=>{beforeEach(()=>{vi.clearAllMocks();setup()})
 it('loads initial data once and renders all coordinated charts',async()=>{renderPage();expect(await screen.findByRole('heading',{name:'Et si un secteur ralentissait demain ?'})).toBeInTheDocument();expect(stress.loadSimulationPageData).toHaveBeenCalledTimes(1);expect(screen.getByTestId('waterfall-chart')).toBeInTheDocument();expect(screen.getByTestId('gdp-before-after-chart')).toBeInTheDocument();expect(screen.getByTestId('composition-chart')).toBeInTheDocument()})
 it('calculates loss, simulated GDP and impact locally without slider API calls',async()=>{renderPage();await screen.findByTestId('shock-slider');expect(screen.getByText('10.00%')).toBeInTheDocument();expect(screen.getAllByText('40').length).toBeGreaterThan(0);expect(screen.getByText('360')).toBeInTheDocument();fireEvent.change(screen.getByTestId('shock-slider'),{target:{value:'75'}});expect(screen.getByText('15.00%')).toBeInTheDocument();expect(stress.simulateSingle).not.toHaveBeenCalled();expect(stress.loadImpactPreview).not.toHaveBeenCalled()})
 it('updates year and sector from cached series',async()=>{const user=userEvent.setup();renderPage();await screen.findByTestId('simulation-year');await user.selectOptions(screen.getByTestId('simulation-year'),'2023');await user.selectOptions(screen.getByTestId('simulation-sector'),'fishing');expect(screen.getByText('2.63%')).toBeInTheDocument();expect(stress.loadSimulationPageData).toHaveBeenCalledTimes(1)})
 it('supports all quick shock buttons',async()=>{const user=userEvent.setup();renderPage();await screen.findByTestId('shock-slider');for(const value of [10,25,50,75,100]){await user.click(screen.getByRole('button',{name:`${value}%`}));expect(screen.getByTestId('shock-slider')).toHaveValue(String(value))}})
 it('selects a sector from the historical chart controls',async()=>{const user=userEvent.setup();renderPage();await screen.findByTestId('simulation-sector');await user.click(screen.getByTestId('composition-select-primary_sector'));expect(screen.getByTestId('simulation-sector')).toHaveValue('primary_sector')})
 it('supports Arabic RTL',async()=>{await i18n.changeLanguage('ar');renderPage();expect(await screen.findByRole('heading',{name:'ماذا لو تباطأ قطاع غداً؟'})).toBeInTheDocument();expect(document.documentElement).toHaveAttribute('dir','rtl')})
 it('shows missing-data and initial backend-unavailable states',async()=>{vi.mocked(stress.loadSimulationPageData).mockResolvedValue({...pageData,seriesByCode:{...pageData.seriesByCode,extractive_activities:[{year:2024,value:null}]}});const first=renderPage();expect(await screen.findAllByText('Valeur manquante')).not.toHaveLength(0);first.unmount();vi.mocked(stress.loadSimulationPageData).mockRejectedValue(new Error('network unavailable'));renderPage();expect(await screen.findByText('Backend indisponible')).toBeInTheDocument()})
})
