import { render, screen } from '@testing-library/react'
import type { ReactNode } from 'react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { LanguageProvider } from '../contexts/LanguageContext'
import { ChartSkeleton, KpiCardSkeleton, TableSkeleton } from '../components/LoadingStates'
import { EconomicTooltip } from '../components/charts/EconomicTooltip'
import { AssistantExperiencePage } from '../pages/AssistantExperiencePage'
import { NotFoundPage } from '../pages/NotFoundPage'
import { ReportsExperiencePage } from '../pages/ReportsExperiencePage'
import { api } from '../services/api'
import { BackendUnavailableBanner, ChartErrorState } from '../components/ErrorStates'
import { Layout } from '../components/Layout'
import i18n from '../i18n'

function providers(children:ReactNode){return <LanguageProvider><MemoryRouter>{children}</MemoryRouter></LanguageProvider>}
it('renders reusable chart, KPI, and table skeletons',()=>{render(providers(<><ChartSkeleton/><KpiCardSkeleton/><TableSkeleton/></>));expect(screen.getByTestId('chart-skeleton')).toBeInTheDocument();expect(screen.getByTestId('kpi-skeleton')).toBeInTheDocument();expect(screen.getByTestId('table-skeleton')).toBeInTheDocument()})
it('renders localized economic tooltip values, shares, and missing observations',()=>{render(providers(<EconomicTooltip active year={2024} items={[{name:'Pêche',value:120,unit:'Millions MRU',share:4.5},{name:'Commerce',value:null}]}/>));expect(screen.getByText(/120 Millions/)).toBeInTheDocument();expect(screen.getByText(/4,5/)).toBeInTheDocument();expect(screen.getByText('Valeur non disponible')).toBeInTheDocument()})
it('shows Assistant typing, disables duplicate submission, and replaces it after success',async()=>{let resolve:(value:unknown)=>void=()=>{};vi.spyOn(api,'post').mockReturnValue(new Promise(r=>{resolve=r}) as never);const user=userEvent.setup();render(providers(<AssistantExperiencePage/>));await user.type(screen.getByLabelText('Votre question'),'Question test');await user.click(screen.getByRole('button',{name:'Interroger'}));expect(screen.getByTestId('assistant-typing')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Interroger'})).toBeDisabled();expect(screen.getAllByText('Question test')).toHaveLength(2);resolve({data:{answer:'Réponse finale',calculation:null,warnings:[],recommendation_plan:null,values_used:[]}});expect(await screen.findByText('Réponse finale')).toBeInTheDocument();expect(screen.queryByTestId('assistant-typing')).not.toBeInTheDocument();vi.restoreAllMocks()})
it('shows a localized Assistant error',async()=>{vi.spyOn(api,'post').mockRejectedValue(new Error('offline'));const user=userEvent.setup();render(providers(<AssistantExperiencePage/>));await user.type(screen.getByLabelText('Votre question'),'Question test');await user.click(screen.getByRole('button',{name:'Interroger'}));expect(await screen.findByRole('alert')).toHaveTextContent('Impossible d’obtenir la réponse');vi.restoreAllMocks()})
it('renders the custom 404 and Home navigation',async()=>{const user=userEvent.setup();render(<LanguageProvider><MemoryRouter initialEntries={['/unknown-page']}><Routes><Route path="*" element={<NotFoundPage/>}/><Route path="/" element={<h1>Accueil cible</h1>}/></Routes></MemoryRouter></LanguageProvider>);expect(screen.getByRole('heading',{name:'Page introuvable'})).toBeInTheDocument();await user.click(screen.getByRole('link',{name:'Accueil'}));expect(screen.getByText('Accueil cible')).toBeInTheDocument()})
it('renders the Arabic 404 with RTL direction',async()=>{await i18n.changeLanguage('ar');render(providers(<NotFoundPage/>));expect(screen.getByRole('heading',{name:'الصفحة غير موجودة'})).toBeInTheDocument();expect(document.documentElement).toHaveAttribute('dir','rtl')})
it('offers localized chart retry and backend-unavailable states',async()=>{const retry=vi.fn();render(providers(<><BackendUnavailableBanner/><ChartErrorState details="offline" onRetry={retry}/></>));expect(screen.getAllByRole('alert')).toHaveLength(2);await userEvent.click(screen.getByRole('button',{name:'Réessayer'}));expect(retry).toHaveBeenCalledOnce()})
it('opens and closes the compact navigation without leaving body scrolling locked',async()=>{Object.defineProperty(window,'innerWidth',{value:320,writable:true,configurable:true});const user=userEvent.setup();render(<LanguageProvider><MemoryRouter><Routes><Route element={<Layout/>}><Route index element={<p>Accueil mobile</p>}/><Route path="simulate" element={<p>Simulation mobile</p>}/></Route></Routes></MemoryRouter></LanguageProvider>);await user.click(screen.getByRole('button',{name:'Ouvrir le menu'}));expect(document.body.style.overflow).toBe('hidden');await user.click(screen.getAllByRole('link',{name:'Simuler'}).at(-1)!);expect(await screen.findByText('Simulation mobile')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Fermer le menu'})).not.toBeInTheDocument();expect(document.body.style.overflow).toBe('')})
it('shows a spinner inside the PDF download button',async()=>{vi.spyOn(api,'get').mockResolvedValue({data:[{id:1,code:'gdp_activity_market_prices',name_fr:'PIB',name_ar:'الناتج',category:'gdp',hierarchy_level:1,unit:'MRU',source_side:'activity',is_aggregate:true,is_alias:false}]} as never);vi.spyOn(api,'post').mockReturnValue(new Promise(()=>{}) as never);render(providers(<ReportsExperiencePage/>));const button=await screen.findByRole('button',{name:'Télécharger'});await userEvent.click(button);expect(screen.getByTestId('button-spinner')).toBeInTheDocument();expect(button).toBeDisabled();vi.restoreAllMocks()})
