import { useMemo, useState } from 'react'
import type { Indicator } from '../../types/economic'
import { targetConflict } from '../../utils/simulation'
import { useCopy } from '../DataDisplay'

export function TargetSectorSelector({sectors,affected,targets,onChange}:{sectors:Indicator[];affected:string;targets:string[];onChange:(codes:string[])=>void}){
 const c=useCopy();const [query,setQuery]=useState(''),[message,setMessage]=useState('')
 const available=useMemo(()=>sectors.filter(item=>!targets.includes(item.code)&&`${item.name_fr} ${item.name_ar??''} ${item.code}`.toLowerCase().includes(query.toLowerCase())),[query,sectors,targets])
 const add=(code:string)=>{if(targets.length>=4){setMessage(c('Maximum de quatre secteurs cibles.','الحد الأقصى أربعة قطاعات مستهدفة.'));return}const conflict=targetConflict(affected,targets,code);if(conflict){setMessage(conflict==='affected-overlap'?c('Le secteur touché ou sa hiérarchie ne peut pas se compenser lui-même.','لا يمكن للقطاع المتأثر أو تسلسله الهرمي تعويض نفسه.'):c('Cette combinaison parent-enfant créerait un double comptage.','سيؤدي الجمع بين الأصل والفرع إلى احتساب مزدوج.'));return}setMessage('');onChange([...targets,code]);setQuery('')}
 return <div className="grid gap-3"><label className="grid gap-1 text-sm font-semibold"><span>{c('Rechercher un secteur cible','البحث عن قطاع مستهدف')}</span><input value={query} onChange={event=>setQuery(event.target.value)} className="min-h-11 min-w-0 rounded-xl border px-3 py-2.5" placeholder={c('Nom ou code du secteur…','اسم القطاع أو رمزه…')}/></label>{query&&<div className="max-h-48 overflow-y-auto rounded-xl border bg-white p-2" role="listbox">{available.length?available.slice(0,8).map(item=><button type="button" role="option" aria-selected="false" onClick={()=>add(item.code)} className="block min-h-11 w-full rounded-lg px-3 py-2 text-start text-sm hover:bg-slate-50" key={item.code}>{c(item.name_fr,item.name_ar??item.name_fr)}</button>):<p className="p-3 text-sm text-slate-500">{c('Aucun secteur compatible.','لا يوجد قطاع متوافق.')}</p>}</div>}<div className="flex flex-wrap gap-2">{targets.map(code=>{const item=sectors.find(sector=>sector.code===code);return <button type="button" aria-label={c(`Retirer ${item?.name_fr??code}`,`إزالة ${item?.name_ar??code}`)} onClick={()=>onChange(targets.filter(value=>value!==code))} className="min-h-11 rounded-full bg-mauritania-50 px-3 py-2 text-sm font-bold text-mauritania-800" key={code}>{c(item?.name_fr??code,item?.name_ar??item?.name_fr??code)} ×</button>})}</div>{message&&<p role="alert" className="text-sm font-semibold text-red-700">{message}</p>}<p className="text-xs text-slate-500">{c(`${targets.length}/4 secteurs sélectionnés. Les parents et enfants incompatibles sont bloqués.`,`${targets.length}/4 قطاعات محددة. تُمنع تركيبات الأصل والفرع غير المتوافقة.`)}</p></div>
}
