import { useState } from 'react'
import { api } from '../services/api'
import { useLanguage } from '../contexts/LanguageContext'
import { Badge, DataTable, NumberValue, useCopy } from '../components/DataDisplay'
import { PageContainer, PageHeader, Panel, WarningBanner } from '../components/Page'
import { ResponseTimeline } from '../components/recommendations/ResponseTimeline'
import { AssistantTypingIndicator } from '../components/assistant/AssistantTypingIndicator'
import type { RecommendationResponse } from '../types/economic'
type Answer={answer:string;calculation:string|null;warnings:string[];recommendation_plan:RecommendationResponse|null;values_used:Array<{indicator_name:string;year:number;value:number;source_file:string;worksheet:string}>}
export function AssistantExperiencePage(){const c=useCopy();const {language}=useLanguage();const [question,setQuestion]=useState(''),[submitted,setSubmitted]=useState(''),[answer,setAnswer]=useState<Answer|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(loading)return;setLoading(true);setError('');setAnswer(null);setSubmitted(question);try{setAnswer((await api.post<Answer>('/api/assistant/query',{question,language})).data)}catch{setError(c('Impossible d’obtenir la réponse. Vérifiez la connexion puis réessayez.','تعذر الحصول على الإجابة. تحقق من الاتصال ثم أعد المحاولة.'))}finally{setLoading(false)}}
 return <PageContainer><PageHeader eyebrow={c('Données, calculs et règles','البيانات والحسابات والقواعد')} title={c('Assistant économique','المساعد الاقتصادي')} description={c('Distingue les observations, les impacts calculés et les options de réponse.','يميّز بين المشاهدات والآثار المحسوبة وخيارات الاستجابة.')}/><form className="mt-7 grid gap-3" onSubmit={submit}><label className="font-semibold"><span>{c('Votre question','سؤالك')}</span><textarea required value={question} onChange={e=>setQuestion(e.target.value)} className="mt-2 min-h-28 w-full rounded-2xl border p-4 focus:ring-2" placeholder={c('Posez votre question…','اكتب سؤالك…')}/></label><button disabled={loading} className="min-h-11 w-fit rounded-xl bg-mauritania-700 px-5 py-3 font-bold text-white disabled:opacity-60">{c('Interroger','اسأل')}</button></form>{submitted&&<section className="mt-5 rounded-2xl bg-mauritania-50 p-4"><p className="text-xs font-bold uppercase text-mauritania-700">{c('Votre question','سؤالك')}</p><p className="mt-1">{submitted}</p></section>}{loading&&<AssistantTypingIndicator/>}{error&&<div role="alert" className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4">{error}</div>}{answer&&<Panel className="mt-6" title={c('Réponse structurée','إجابة منظمة')}><div aria-live="polite"><p className="leading-8">{answer.answer}</p></div>{answer.recommendation_plan&&<><div className="my-5 flex items-center gap-3"><strong>{c('Risque du scénario','مخاطر السيناريو')}</strong><Badge tone={answer.recommendation_plan.risk_level==='critical'?'danger':'warning'}>{answer.recommendation_plan.risk_level==='critical'?c('Critique','حرجة'):c('Élevé','مرتفع')}</Badge></div><ResponseTimeline recommendations={answer.recommendation_plan.recommendations}/></>}{answer.calculation&&<details className="mt-4"><summary>{c('Calcul technique','الحساب التقني')}</summary><pre className="mt-2 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-white">{answer.calculation}</pre></details>}<h3 className="mt-6 font-bold">{c('Données nationales observées','بيانات الحسابات الوطنية المرصودة')}</h3><DataTable headers={[c('Indicateur','المؤشر'),c('Année','السنة'),c('Valeur','القيمة'),c('Fichier / feuille','الملف / الورقة')]} rows={answer.values_used.map(v=>[v.indicator_name,v.year,<NumberValue value={v.value}/>,`${v.source_file} — ${v.worksheet}`])}/>{answer.warnings.length>0&&<div className="mt-4"><WarningBanner title={c('Limites des données','حدود البيانات')}>{answer.warnings.join(' ')}</WarningBanner></div>}</Panel>}</PageContainer>}
