import { ArrowRight, Bot, BrainCircuit, ChartNoAxesCombined, Check, Database, FileText, Gauge, LineChart, Play, ShieldCheck, Sparkles, Target, WandSparkles } from 'lucide-react'
import { motion, useReducedMotion } from 'framer-motion'
import { Link } from 'react-router-dom'
import { Reveal, HoverCard } from '../components/ui/Motion'
import { useCopy } from '../components/DataDisplay'

const featureIcons = [BrainCircuit, ChartNoAxesCombined, Target, FileText] as const
const workflowIcons = [Database, WandSparkles, BrainCircuit, LineChart, Target, FileText] as const

function DashboardPreview() {
  const reduced = useReducedMotion()
  const c = useCopy()
  return <motion.div aria-label="Aperçu du tableau de bord économique" className="relative mx-auto w-full max-w-[540px]" animate={reduced ? {} : { y: [0, -8, 0] }} transition={{ duration: 6, repeat: Infinity, ease: 'easeInOut' }}>
    <div className="absolute -inset-8 -z-10 rounded-full bg-emerald-300/30 blur-3xl" />
    <div className="overflow-hidden rounded-[28px] border border-white/70 bg-white/80 p-3 shadow-[0_35px_90px_-35px_rgba(7,93,59,.55)] backdrop-blur-xl sm:p-4">
      <div className="flex items-center justify-between border-b border-slate-100 px-2 pb-3"><div className="flex gap-1.5"><i className="h-2.5 w-2.5 rounded-full bg-rose-400"/><i className="h-2.5 w-2.5 rounded-full bg-amber-400"/><i className="h-2.5 w-2.5 rounded-full bg-emerald-500"/></div><span className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">MEIP / {c('intelligence', 'الذكاء')}</span></div><p className="mx-2 mt-3 rounded-md bg-amber-50 px-2 py-1 text-[9px] font-black tracking-wider text-amber-800">DEMO DATA · {c('aperçu d’interface', 'معاينة للواجهة')}</p>
      <div className="grid gap-3 pt-3 sm:grid-cols-[1.35fr_.85fr]"><div className="rounded-2xl bg-slate-950 p-4 text-white"><div className="flex items-center justify-between"><span className="text-xs text-slate-400">PIB · 2024</span><span className="rounded-full bg-emerald-400/15 px-2 py-1 text-[10px] font-bold text-emerald-300">+ {c('direct', 'مباشر')}</span></div><p className="mt-3 text-2xl font-black tracking-tight">429 701</p><div className="mt-5 flex h-20 items-end gap-1.5">{[28, 37, 31, 46, 42, 55, 51, 68, 73, 65, 84, 92].map((h, i)=><motion.span key={i} className="w-full rounded-t bg-gradient-to-t from-emerald-500 to-cyan-300" initial={reduced ? false : { height: 0 }} animate={{ height: `${h}%` }} transition={{ delay: .15 + i * .04, duration: .6 }}/>)}</div></div><div className="space-y-3"><div className="rounded-2xl border border-slate-100 bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{c('Insight IA', 'تحليل الذكاء الاصطناعي')}</p><p className="mt-2 text-xs font-semibold leading-5 text-slate-700">{c('Les services restent le premier contributeur.', 'تظل الخدمات المساهم الأول.')}</p></div><div className="rounded-2xl bg-emerald-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-emerald-700">{c('Prévision', 'توقع')}</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-emerald-100"><motion.div className="h-full rounded-full bg-emerald-500" initial={{ width: 0 }} animate={{ width: '72%' }} transition={{ duration: 1.1, delay: .5 }}/></div></div></div></div>
    </div>
  </motion.div>
}

export function Home() {
  const c = useCopy()
  const stats = [[c('27', '27'), c('années de données économiques', 'سنة من البيانات الاقتصادية')], [c('40+', '+40'), c('indicateurs canoniques', 'مؤشرا معياريا')], [c('IA', 'ذكاء اصطناعي'), c('insights à la demande', 'تحليلات عند الطلب')], [c('PDF + CSV', 'PDF + CSV'), c('rapports exportables', 'تقارير قابلة للتصدير')]]
  const features = [[c('Assistant économique IA', 'مساعد اقتصادي بالذكاء الاصطناعي'), c('Posez vos questions en langage naturel et obtenez une réponse ancrée dans les données importées.', 'اطرح أسئلتك بلغة طبيعية واحصل على إجابات تستند إلى البيانات المستوردة.')], [c('Prévisions transparentes', 'توقعات شفافة'), c('Explorez des projections expérimentales, leurs méthodes et leurs limites.', 'استكشف توقعات تجريبية مع منهجياتها وحدودها.')], [c('Simulations utiles', 'محاكاة عملية'), c('Mesurez l’impact direct de scénarios économiques sur le PIB et les secteurs.', 'قِس الأثر المباشر للسيناريوهات الاقتصادية على الناتج والقطاعات.')], [c('Rapports instantanés', 'تقارير فورية'), c('Exportez des analyses bilingues en PDF ou CSV, avec source et période.', 'صدّر تحليلات ثنائية اللغة بصيغة PDF أو CSV مع المصدر والفترة.')]]
  const workflow = [c('Données économiques', 'البيانات الاقتصادية'), c('Nettoyage', 'التنظيف'), c('Base de connaissances', 'قاعدة المعرفة'), c('Analyse IA', 'تحليل الذكاء الاصطناعي'), c('Prévisions', 'التوقعات'), c('Recommandations & rapports', 'التوصيات والتقارير')]
  return <main className="overflow-hidden">
    <section className="relative isolate"><div className="absolute inset-0 -z-10 hero-grid"/><div className="absolute -left-24 top-8 -z-10 h-72 w-72 rounded-full bg-gold-200/40 blur-3xl"/><div className="absolute right-0 top-20 -z-10 h-80 w-80 rounded-full bg-emerald-200/45 blur-3xl"/>
      <div className="mx-auto grid max-w-7xl items-center gap-14 px-4 pb-20 pt-14 sm:px-6 sm:pb-28 sm:pt-24 lg:grid-cols-[1.05fr_.95fr] lg:px-8"><Reveal><div className="max-w-3xl"><p className="eyebrow"><Sparkles size={14}/>{c('Intelligence économique propulsée par l’IA', 'ذكاء اقتصادي مدعوم بالذكاء الاصطناعي')}</p><h1 className="mt-6 text-balance text-5xl font-black leading-[.98] tracking-[-.055em] text-slate-950 sm:text-6xl lg:text-7xl">{c('Comprendre l’économie mauritanienne avec l’IA.', 'افهم اقتصاد موريتانيا بالذكاء الاصطناعي.')}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">{c('Une plateforme d’intelligence économique qui transforme les données nationales en prévisions, recommandations, rapports et analyses décisionnelles.', 'منصة للذكاء الاقتصادي تحول البيانات الوطنية إلى توقعات وتوصيات وتقارير وتحليلات لدعم القرار.')}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/assistant" className="button-primary"><Bot size={18}/>{c('Essayer l’assistant IA', 'جرّب المساعد الذكي')}<ArrowRight size={17}/></Link><a href="#demo" className="button-secondary"><Play size={16} fill="currentColor"/>{c('Voir la démo', 'شاهد العرض')}</a></div><div className="mt-10 flex items-center gap-3 text-sm text-slate-500"><span className="grid h-6 w-6 place-items-center rounded-full bg-emerald-100 text-emerald-700"><Check size={14}/></span>{c('Données traçables · prix courants clairement signalés', 'بيانات قابلة للتتبع · مع توضيح الأسعار الجارية')}</div></div></Reveal><Reveal delay={.12}><DashboardPreview/></Reveal></div>
    </section>
    <section className="border-y border-slate-200/80 bg-white/70"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-y divide-slate-100 px-4 sm:grid-cols-4 sm:divide-y-0 sm:px-6 lg:px-8">{stats.map(([value,label])=><div key={label} className="px-4 py-7 text-center sm:px-6"><p className="text-2xl font-black tracking-tight text-mauritania-700 sm:text-3xl">{value}</p><p className="mt-1 text-xs font-semibold leading-5 text-slate-500 sm:text-sm">{label}</p></div>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><Reveal><div className="max-w-2xl"><p className="eyebrow">01 · {c('Pourquoi MEIP', 'لماذا MEIP')}</p><h2 className="section-title">{c('Des comptes nationaux aux décisions plus claires.', 'من الحسابات الوطنية إلى قرارات أوضح.')}</h2><p className="section-copy">{c('Les informations économiques sont riches mais difficiles à transformer en réponses utilisables. MEIP rassemble exploration, analyse et export dans une expérience bilingue claire.', 'المعلومات الاقتصادية غنية لكنها صعبة التحويل إلى إجابات قابلة للاستخدام. تجمع MEIP الاستكشاف والتحليل والتصدير في تجربة ثنائية اللغة وواضحة.')}</p></div></Reveal><div className="mt-10 grid gap-4 md:grid-cols-3"><HoverCard className="premium-card p-6"><Gauge className="text-mauritania-700"/><h3 className="mt-5 text-lg font-bold">{c('Le problème', 'المشكلة')}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{c('Des tableaux complexes, des sources dispersées et peu de moyens de comparer les évolutions.', 'جداول معقدة ومصادر متفرقة وقلة في أدوات مقارنة التطورات.')}</p></HoverCard><HoverCard className="premium-card p-6"><BrainCircuit className="text-blue-600"/><h3 className="mt-5 text-lg font-bold">{c('La solution', 'الحل')}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{c('Une couche IA et analytique qui rend les données économiques navigables et actionnables.', 'طبقة تحليل وذكاء اصطناعي تجعل البيانات الاقتصادية قابلة للاستكشاف والتنفيذ.')}</p></HoverCard><HoverCard className="premium-card p-6"><ShieldCheck className="text-gold-600"/><h3 className="mt-5 text-lg font-bold">{c('La confiance', 'الثقة')}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{c('Chaque résultat conserve sa source, son unité et les limites des données publiées.', 'تحافظ كل نتيجة على مصدرها ووحدتها وحدود البيانات المنشورة.')}</p></HoverCard></div></section>
    <section className="bg-slate-950 py-20 text-white sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><Reveal><p className="eyebrow border-white/10 bg-white/10 text-emerald-200">02 · {c('Le moteur IA', 'محرك الذكاء الاصطناعي')}</p><h2 className="mt-5 max-w-2xl text-3xl font-black tracking-tight sm:text-5xl">{c('L’IA n’est pas une option. C’est le fil conducteur.', 'الذكاء الاصطناعي ليس خيارا. إنه المحرك الأساسي.')}</h2></Reveal><div className="mt-12 grid gap-3 md:grid-cols-6">{workflow.map((label,index)=>{const Icon=workflowIcons[index];return <div key={label} className="relative"><Reveal delay={index*.06}><div className="rounded-2xl border border-white/10 bg-white/[.06] p-4 backdrop-blur"><Icon size={19} className="text-gold-300"/><p className="mt-5 text-sm font-bold leading-5">{label}</p></div></Reveal>{index<workflow.length-1&&<ArrowRight className="absolute -right-4 top-1/2 z-10 hidden -translate-y-1/2 text-emerald-300 md:block" size={18}/>}</div>})}</div><div className="mt-10 rounded-3xl border border-emerald-300/20 bg-gradient-to-r from-emerald-500/15 to-blue-500/15 p-6 sm:flex sm:items-center sm:justify-between"><div><p className="font-bold">{c('Génération d’insights en cours', 'يتم الآن توليد التحليلات')}</p><p className="mt-1 text-sm text-slate-300">{c('L’assistant relie la question aux séries réellement disponibles.', 'يربط المساعد السؤال بالسلاسل المتاحة بالفعل.')}</p></div><div className="mt-4 flex items-center gap-2 sm:mt-0"><span className="thinking-dot"/><span className="thinking-dot [animation-delay:150ms]"/><span className="thinking-dot [animation-delay:300ms]"/></div></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><Reveal><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div className="max-w-2xl"><p className="eyebrow">03 · {c('Fonctionnalités IA', 'ميزات الذكاء الاصطناعي')}</p><h2 className="section-title">{c('Pensé pour explorer. Conçu pour décider.', 'مصمم للاستكشاف. ومبني للقرار.')}</h2></div><Link className="text-sm font-bold text-mauritania-700 hover:text-mauritania-900" to="/dashboard">{c('Ouvrir le tableau de bord', 'افتح لوحة المعلومات')} <ArrowRight className="inline" size={15}/></Link></div></Reveal><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{features.map(([title,description],index)=>{const Icon=featureIcons[index];return <HoverCard key={title} className="premium-card group p-6"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-slate-100 text-slate-800 transition group-hover:bg-mauritania-700 group-hover:text-white"><Icon size={20}/></span><h3 className="mt-6 font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></HoverCard>})}</div></section>
    <section id="demo" className="relative bg-emerald-50/70 py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><Reveal><div><p className="eyebrow">04 · {c('Démo interactive', 'عرض تفاعلي')}</p><h2 className="section-title">{c('Du signal à la recommandation, en quelques instants.', 'من الإشارة إلى التوصية، في لحظات.')}</h2><p className="section-copy">{c('Naviguez dans les indicateurs, comparez les évolutions, simulez des chocs et produisez des rapports sans perdre le contexte des données.', 'تنقل بين المؤشرات وقارن التطورات وحاكي الصدمات وأنشئ التقارير دون فقدان سياق البيانات.')}</p><Link to="/simulate" className="button-primary mt-7">{c('Explorer les simulations', 'استكشف المحاكاة')}<ArrowRight size={17}/></Link></div></Reveal><Reveal delay={.1}><div className="premium-card overflow-hidden p-3"><div className="rounded-2xl bg-gradient-to-br from-mauritania-900 to-navy-950 p-6 text-white"><div className="flex items-center justify-between"><span className="text-sm font-bold">{c('Recommandation IA', 'توصية الذكاء الاصطناعي')}</span><Sparkles className="text-gold-300"/></div><p className="mt-7 max-w-sm text-xl font-bold leading-8">{c('Surveiller l’évolution des activités extractives et comparer les scénarios sectoriels.', 'راقب تطور الأنشطة الاستخراجية وقارن السيناريوهات القطاعية.')}</p><div className="mt-8 flex gap-2"><span className="rounded-full bg-white/10 px-3 py-1 text-xs">{c('Source', 'المصدر')}: ANSADE/CN</span><span className="rounded-full bg-white/10 px-3 py-1 text-xs">2024</span></div></div></div></Reveal></div></section>
    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><Reveal><div className="rounded-[28px] bg-gradient-to-br from-mauritania-700 to-navy-950 px-7 py-12 text-center text-white shadow-2xl sm:px-12"><p className="eyebrow mx-auto w-fit border-white/10 bg-white/10 text-gold-200">MEIP</p><h2 className="mt-5 text-3xl font-black tracking-tight sm:text-5xl">{c('Une intelligence économique qui reste humaine.', 'ذكاء اقتصادي يظل إنسانيا.')}</h2><p className="mx-auto mt-5 max-w-2xl text-slate-200">{c('Construit pour les analystes, décideurs, chercheurs et citoyens qui veulent comprendre les données avant de les utiliser.', 'مبني للمحللين وصناع القرار والباحثين والمواطنين الذين يريدون فهم البيانات قبل استخدامها.')}</p><Link to="/assistant" className="button-light mt-8">{c('Commencer avec l’IA', 'ابدأ مع الذكاء الاصطناعي')}<ArrowRight size={17}/></Link></div></Reveal></section>
  </main>
}
