import { useState } from 'react'
import { api } from '../services/api'
import { useApi } from '../hooks/useApi'
import { useLanguage } from '../contexts/LanguageContext'
import { Badge, DataTable, Metadata, NumberValue, SelectField, useCopy } from '../components/DataDisplay'
import { KpiCard, PageContainer, PageHeader, Panel, StatePanel, WarningBanner } from '../components/Page'
import { TimeSeriesChart } from '../components/Charts'
import type { Anomaly, Indicator, Point } from '../types/economic'

function options(indicators:Indicator[]|null,c:(a:string,b:string)=>string){return (indicators??[]).filter(i=>!i.is_alias).map(i=><option key={i.code} value={i.code}>{c(i.name_fr,i.name_ar??i.name_fr)}</option>)}

export function AlertsPage(){const c=useCopy();const [code,setCode]=useState('snim_iron'),[severity,setSeverity]=useState('all');const {data:inds}=useApi<Indicator[]>('/api/indicators');const {data,error,loading}=useApi<{alerts:Anomaly[];name_fr:string;name_ar:string|null}>(`/api/analytics/anomalies?indicator=${code}`);const rows=(data?.alerts??[]).filter(a=>severity==='all'||a.severity===severity);return <PageContainer><PageHeader eyebrow={c('Détection déterministe','كشف حتمي')} title={c('Alertes économiques','التنبيهات الاقتصادية')} description={c('Variations inhabituelles détectées dans les séries importées.','تغيرات غير معتادة مكتشفة في السلاسل المستوردة.')} actions={<div className="flex gap-2"><SelectField label={c('Indicateur','المؤشر')} value={code} onChange={setCode}>{options(inds,c)}</SelectField><SelectField label={c('Sévérité','الخطورة')} value={severity} onChange={setSeverity}><option value="all">{c('Toutes','الكل')}</option><option value="high">high</option><option value="moderate">moderate</option></SelectField></div>}/>{loading?<StatePanel state="loading" title={c('Chargement','تحميل')} description="…"/>:error?<StatePanel state="error" title={c('Erreur','خطأ')} description={error.message}/>:rows.length===0?<StatePanel state="empty" title={c('Aucune alerte','لا تنبيهات')} description={c('Aucune anomalie pour ces filtres.','لا شذوذ لهذه المرشحات.')}/>:<Panel className="mt-6" title={c('Alertes détectées','التنبيهات المكتشفة')}><DataTable headers={[c('Sévérité','الخطورة'),c('Année','السنة'),c('Observé','المرصود'),c('Précédent','السابق'),c('Variation','التغير'),c('Explication','التفسير')]} rows={rows.map(a=>[<Badge tone={a.severity==='high'?'danger':'warning'}>{a.severity}</Badge>,a.year,<NumberValue value={a.observed_value}/>,<NumberValue value={a.previous_value}/>,<NumberValue percent value={a.percentage_change}/>,c(a.explanation_fr??'',a.explanation_ar??'')])}/><Metadata/></Panel>}</PageContainer>}

type Forecast={indicator_code:string;name_fr:string;name_ar:string|null;unit:string;historical:Point[];model_name:string;baseline_model:string;horizon_years:number;predicted_values:number[];lower_bounds:number[];upper_bounds:number[];mae:number|null;mape:number|null;reliability:string;observation_count:number;disclaimer_fr:string;disclaimer_ar:string;warnings:string[]}
export function ForecastPage(){const c=useCopy();const [code,setCode]=useState('gdp_activity_market_prices'),[horizon,setHorizon]=useState(3),[result,setResult]=useState<Forecast|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);const {data:inds}=useApi<Indicator[]>('/api/indicators');const run=async()=>{setLoading(true);setError('');try{setResult((await api.post<Forecast>('/api/forecast',{indicator_code:code,horizon})).data)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};const forecastPoints=result?.predicted_values.map((value,i)=>({year:(result.historical.at(-1)?.year??2024)+i+1,value}))??[];return <PageContainer><PageHeader eyebrow={c('Expérimental','تجريبي')} title={c('Prévisions statistiques','التوقعات الإحصائية')} description={c('Backtests chronologiques, comparaison au modèle naïf et horizon limité.','اختبارات زمنية ومقارنة بالنموذج الساذج وأفق محدود.')} actions={<div className="grid gap-2 sm:grid-cols-3"><SelectField label={c('Indicateur','المؤشر')} value={code} onChange={setCode}>{options(inds,c)}</SelectField><SelectField label={c('Horizon','الأفق')} value={horizon} onChange={v=>setHorizon(+v)}><option>1</option><option>2</option><option>3</option></SelectField><button onClick={run} className="self-end rounded-xl bg-mauritania-700 px-4 py-2.5 font-bold text-white">{c('Calculer','احسب')}</button></div>}/>{loading&&<StatePanel state="loading" title={c('Calcul','حساب')} description="…"/>}{error&&<StatePanel state="error" title={c('Erreur','خطأ')} description={error}/>} {result&&<><div className="mt-6"><WarningBanner title={c('Prévision non officielle','توقع غير رسمي')}>{c(result.disclaimer_fr,result.disclaimer_ar)}</WarningBanner></div><div className="mt-6 grid gap-4 sm:grid-cols-4"><KpiCard label={c('Modèle','النموذج')} value={result.model_name}/><KpiCard label="MAE" value={result.mae?.toFixed(2)??'—'}/><KpiCard label="MAPE" value={result.mape==null?'—':`${result.mape.toFixed(2)} %`}/><KpiCard label={c('Fiabilité','الموثوقية')} value={result.reliability}/></div><Panel className="mt-6" title={c('Historique et estimations','التاريخ والتقديرات')}><TimeSeriesChart series={[{name:c('Observé','مرصود'),points:result.historical},{name:c('Estimé','مقدر'),points:forecastPoints}]}/><Metadata unit={result.unit}/></Panel></>}</PageContainer>}

type AssistantAnswer={language:string;intent:string;supported:boolean;answer:string;calculation:string|null;warnings:string[];values_used:Array<{indicator_code:string;year:number;value:number;source_file:string;worksheet:string;source_side:string;unit:string}>}
export function AssistantPage(){const c=useCopy();const {language}=useLanguage();const [question,setQuestion]=useState(''),[answer,setAnswer]=useState<AssistantAnswer|null>(null),[loading,setLoading]=useState(false);const examples=language==='ar'?['ماذا سيحدث إذا توقف قطاع التعدين سنة 2024؟','ما الحلول المقترحة لأزمة في قطاع الصيد؟']:['Et si les mines s’arrêtaient en 2024 ?','Que peut faire la Mauritanie si les mines s’arrêtent ?'];const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);try{setAnswer((await api.post<AssistantAnswer>('/api/assistant/query',{question,language})).data)}finally{setLoading(false)}};return <PageContainer><PageHeader eyebrow={c('Sans LLM externe','دون نموذج خارجي')} title={c('Assistant économique','المساعد الاقتصادي')} description={c('Réponses déterministes avec preuves, calculs et provenance.','إجابات حتمية مع الأدلة والحسابات والمصدر.')}/><form className="mt-7 grid gap-3" onSubmit={submit}><textarea required value={question} onChange={e=>setQuestion(e.target.value)} className="min-h-28 rounded-2xl border border-slate-300 bg-white p-4" placeholder={c('Posez votre question…','اكتب سؤالك…')}/><div className="flex flex-wrap gap-2">{examples.map(x=><button type="button" onClick={()=>setQuestion(x)} className="rounded-full bg-slate-100 px-3 py-2 text-sm" key={x}>{x}</button>)}</div><button className="w-fit rounded-xl bg-mauritania-700 px-5 py-3 font-bold text-white">{c('Interroger','اسأل')}</button></form>{loading&&<StatePanel state="loading" title={c('Analyse','تحليل')} description="…"/>}{answer&&<Panel className="mt-6" title={c('Réponse structurée','إجابة منظمة')}><p className="leading-8">{answer.answer}</p>{answer.calculation&&<pre className="mt-4 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-white">{answer.calculation}</pre>}<DataTable headers={[c('Indicateur','المؤشر'),c('Année','السنة'),c('Valeur','القيمة'),c('Fichier / feuille','الملف / الورقة')]} rows={answer.values_used.map(v=>[v.indicator_code,v.year,<NumberValue value={v.value}/>,`${v.source_file} — ${v.worksheet}`])}/></Panel>}</PageContainer>}

export function ReportsPage(){const c=useCopy();const {language}=useLanguage();const [code,setCode]=useState('gdp_activity_market_prices'),[format,setFormat]=useState('pdf'),[busy,setBusy]=useState(false);const {data:inds}=useApi<Indicator[]>('/api/indicators');const download=async()=>{setBusy(true);try{const r=await api.post('/api/reports/generate',{indicator_code:code,start_year:1998,end_year:2024,language,format},{responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download=`meip_${code}.${format}`;a.click();URL.revokeObjectURL(url)}finally{setBusy(false)}};return <PageContainer><PageHeader eyebrow={c('Exports traçables','صادرات قابلة للتتبع')} title={c('Rapports','التقارير')} description={c('Générez un PDF bilingue RTL/LTR ou un CSV UTF-8 à partir des données réelles.','أنشئ PDF ثنائي اللغة أو CSV من البيانات الحقيقية.')} actions={<div className="grid gap-2 sm:grid-cols-3"><SelectField label={c('Indicateur','المؤشر')} value={code} onChange={setCode}>{options(inds,c)}</SelectField><SelectField label={c('Format','الصيغة')} value={format} onChange={setFormat}><option value="pdf">PDF</option><option value="csv">CSV</option></SelectField><button disabled={busy} onClick={download} className="self-end rounded-xl bg-mauritania-700 px-4 py-2.5 font-bold text-white disabled:opacity-50">{busy?c('Génération…','جار الإنشاء…'):c('Télécharger','تنزيل')}</button></div>}/></PageContainer>}

type Dataset={code:string;name_fr:string;name_ar:string|null;original_filename:string;worksheet_name:string;source_name:string;unit:string;price_type:string;frequency:string;start_year:number|null;end_year:number|null;imported_at:string;validation_status:string}
export function CataloguePage(){const c=useCopy();const {data,error,loading}=useApi<Dataset[]>('/api/datasets');const {data:inds}=useApi<Indicator[]>('/api/indicators');if(loading)return <PageContainer><StatePanel state="loading" title={c('Chargement','تحميل')} description="…"/></PageContainer>;if(error)return <PageContainer><StatePanel state="error" title={c('Erreur','خطأ')} description={error.message}/></PageContainer>;return <PageContainer><PageHeader eyebrow={c('Provenance','المصدر')} title={c('Catalogue des données','دليل البيانات')} description={c('Fichiers, feuilles, validation, hiérarchie canonique et alias.','الملفات والأوراق والتحقق والتسلسل الهرمي والأسماء البديلة.')}/><div className="mt-6 grid gap-5 lg:grid-cols-2">{data?.map(d=><Panel title={c(d.name_fr,d.name_ar??d.name_fr)} key={d.code}><dl className="grid grid-cols-2 gap-3 text-sm"><dt>{c('Fichier','الملف')}</dt><dd>{d.original_filename}</dd><dt>{c('Feuille','الورقة')}</dt><dd>{d.worksheet_name}</dd><dt>{c('Période','الفترة')}</dt><dd>{d.start_year}–{d.end_year}</dd><dt>{c('Fréquence','التواتر')}</dt><dd>{d.frequency}</dd><dt>{c('Prix','الأسعار')}</dt><dd>{d.price_type}</dd><dt>{c('Validation','التحقق')}</dt><dd><Badge tone="good">{d.validation_status}</Badge></dd></dl><Metadata source={d.source_name} unit={d.unit}/></Panel>)}</div><Panel className="mt-6" title={c('Hiérarchie des indicateurs','التسلسل الهرمي للمؤشرات')}><DataTable headers={[c('Code canonique','الرمز المعتمد'),c('Nom','الاسم'),c('Niveau','المستوى'),c('Côté','الجانب'),c('Alias','اسم بديل')]} rows={(inds??[]).map(i=>[i.code,c(i.name_fr,i.name_ar??i.name_fr),i.hierarchy_level,i.source_side,i.is_alias?c('Oui','نعم'):c('Non','لا')])}/></Panel></PageContainer>}
