import { useState } from 'react'
import { api } from '../services/api'
import { useApi } from '../hooks/useApi'
import { useLanguage } from '../contexts/LanguageContext'
import type { Indicator } from '../types/economic'
import { SelectField, useCopy } from '../components/DataDisplay'
import { PageContainer, PageHeader } from '../components/Page'
import { ButtonSpinner, KpiCardSkeleton } from '../components/LoadingStates'
import { SectionErrorState } from '../components/ErrorStates'
export function ReportsExperiencePage(){const c=useCopy();const {language}=useLanguage();const {data:indicators,loading,error}=useApi<Indicator[]>('/api/indicators');const [code,setCode]=useState('gdp_activity_market_prices'),[format,setFormat]=useState('pdf'),[busy,setBusy]=useState(false),[downloadError,setDownloadError]=useState('');const download=async()=>{setBusy(true);setDownloadError('');try{const response=await api.post('/api/reports/generate',{indicator_code:code,start_year:1998,end_year:2024,language,format},{responseType:'blob'});const url=URL.createObjectURL(response.data);const link=document.createElement('a');link.href=url;link.download=`meip_${code}.${format}`;link.click();URL.revokeObjectURL(url)}catch{setDownloadError(c('Impossible de générer le rapport.','تعذر إنشاء التقرير.'))}finally{setBusy(false)}}
 return <PageContainer><PageHeader eyebrow={c('Exports traçables','صادرات قابلة للتتبع')} title={c('Rapports','التقارير')} description={c('Générez un PDF bilingue ou un CSV depuis les données réelles.','أنشئ PDF ثنائي اللغة أو CSV من البيانات الحقيقية.')}/>{loading?<div className="mt-6"><KpiCardSkeleton/></div>:error?<div className="mt-6"><SectionErrorState details={error.message} onRetry={()=>window.location.reload()}/></div>:<><div className="mt-6 grid gap-3 rounded-2xl border bg-white p-5 sm:grid-cols-3"><SelectField label={c('Indicateur','المؤشر')} value={code} onChange={setCode}>{(indicators??[]).filter(i=>!i.is_alias).map(i=><option value={i.code} key={i.code}>{c(i.name_fr,i.name_ar??i.name_fr)}</option>)}</SelectField><SelectField label={c('Format','الصيغة')} value={format} onChange={setFormat}><option value="pdf">PDF</option><option value="csv">CSV</option></SelectField><button disabled={busy} onClick={()=>void download()} className="inline-flex min-h-11 items-center justify-center gap-2 self-end rounded-xl bg-mauritania-700 px-4 py-2.5 font-bold text-white disabled:opacity-60">{busy&&<ButtonSpinner/>}{busy?c('Génération…','جارٍ الإنشاء…'):c('Télécharger','تنزيل')}</button></div>{downloadError&&<div className="mt-4"><SectionErrorState onRetry={()=>void download()}/></div>}</>}</PageContainer>}
