import { useEffect, useMemo, useState } from 'react'
import { GdpCompositionChart } from '../components/charts/GdpCompositionChart'
import { GdpShockWaterfallChart } from '../components/charts/GdpShockWaterfallChart'
import { GdpBeforeAfterChart } from '../components/charts/GdpBeforeAfterChart'
import { ResponseTimeline } from '../components/recommendations/ResponseTimeline'
import { ScenarioForm, type ScenarioPreset } from '../components/simulation/ScenarioForm'
import { Badge, CurrentPriceWarning, Metadata, useCopy } from '../components/DataDisplay'
import { KpiCard, PageContainer, PageHeader, Panel, StatePanel, WarningBanner } from '../components/Page'
import { useLanguage } from '../contexts/LanguageContext'
import { generateRecommendations } from '../services/recommendations'
import { loadSimulationPageData } from '../services/stressTest'
import type { RecommendationResponse } from '../types/economic'
import { calculateSingleSectorShock, scenarioRisk } from '../utils/simulation'

const presets:ScenarioPreset[]=[{code:'extractive_stop',fr:'Arrêt extractif complet',ar:'توقف الاستخراج كلياً',sector:'extractive_activities',shock:100},{code:'fishing_half',fr:'Pêche −50%',ar:'الصيد −50٪',sector:'fishing',shock:50},{code:'construction_quarter',fr:'BTP −25%',ar:'البناء −25٪',sector:'construction_public_works',shock:25}]
const previewActions={
 immediate:['Maintenir les opérations et infrastructures essentielles.','الحفاظ على العمليات والبنية التحتية الأساسية.'],
 stabilization:['Rétablir les intrants et soutenir conditionnellement les opérateurs viables.','استعادة المدخلات ودعم المشغلين القابلين للاستمرار بشروط.'],
 recovery:['Moderniser les équipements et reconstruire la capacité productive.','تحديث المعدات وإعادة بناء القدرة الإنتاجية.'],
 structural:['Diversifier la base productive et renforcer la résilience énergétique et financière.','تنويع القاعدة الإنتاجية وتعزيز مرونة الطاقة والتمويل.'],
} as const
function volatility(points:Array<{year:number;value:number|null}>){const rates=points.slice(1).flatMap((point,index)=>{const previous=points[index];return point.year===previous.year+1&&point.value!=null&&previous.value!=null&&previous.value!==0?[(point.value-previous.value)/Math.abs(previous.value)*100]:[]});if(rates.length<2)return null;const mean=rates.reduce((a,b)=>a+b,0)/rates.length;return Math.sqrt(rates.reduce((s,v)=>s+(v-mean)**2,0)/(rates.length-1))}
function previewPriority(horizon:string,risk:string|null){if(horizon==='immediate')return risk??'low';if(horizon==='stabilization')return risk==='critical'||risk==='high'?'high':'medium';return 'medium'}

export function SimulationAndReactionPage(){const c=useCopy();useLanguage();const [loaded,setLoaded]=useState<Awaited<ReturnType<typeof loadSimulationPageData>>|null>(null);const [initialError,setInitialError]=useState('');const [year,setYear]=useState(2024),[sectorCode,setSectorCode]=useState('extractive_activities'),[shockPercent,setShockPercent]=useState(50);const [plan,setPlan]=useState<RecommendationResponse|null>(null),[planBusy,setPlanBusy]=useState(false),[planError,setPlanError]=useState('')
 useEffect(()=>{let active=true;void loadSimulationPageData().then(result=>{if(active){setLoaded(result);setYear(result.years.at(-1)??2024)}}).catch(reason=>active&&setInitialError(reason instanceof Error?reason.message:String(reason)));return()=>{active=false}},[])
 const baseline=loaded?.gdpSeries.find(p=>p.year===year)?.value??null;const sectorValue=loaded?.seriesByCode[sectorCode]?.find(p=>p.year===year)?.value??null
 const calculation=useMemo(()=>{try{return {result:calculateSingleSectorShock({baselineGdp:baseline,sectorValue,shockRate:shockPercent/100}),error:''}}catch(reason){return {result:null,error:reason instanceof Error?reason.message:String(reason)}}},[baseline,sectorValue,shockPercent]);const risk=calculation.result?scenarioRisk(calculation.result.directImpactPercentage):null;const selected=loaded?.sectors.find(i=>i.code===sectorCode);const vol=useMemo(()=>volatility(loaded?.seriesByCode[sectorCode]??[]),[loaded,sectorCode])
 const choosePreset=(code:string)=>{const p=presets.find(x=>x.code===code);if(p){setSectorCode(p.sector);setShockPercent(p.shock)}};const reset=()=>{setYear(2024);setSectorCode('extractive_activities');setShockPercent(50);setPlan(null)};const advanced=async()=>{setPlanBusy(true);setPlanError('');try{setPlan(await generateRecommendations(year,sectorCode,shockPercent,'one_year'))}catch(reason){setPlanError(reason instanceof Error?reason.message:String(reason))}finally{setPlanBusy(false)}}
 if(!loaded&&!initialError)return <PageContainer><StatePanel state="loading" title={c('Chargement initial','التحميل الأولي')} description={c('Mise en cache des séries du PIB et des secteurs…','تخزين سلاسل الناتج والقطاعات…')}/></PageContainer>;if(initialError)return <PageContainer><StatePanel state="error" title={c('Backend indisponible','الخادم غير متاح')} description={initialError}/></PageContainer>
 return <PageContainer><PageHeader eyebrow={c('Simulation instantanée côté navigateur','محاكاة فورية في المتصفح')} title={c('Et si un secteur ralentissait demain ?','ماذا لو تباطأ قطاع غداً؟')} description={c('Chaque contrôle recalcule immédiatement l’impact comptable direct, sans requête API.','يعيد كل عنصر تحكم حساب الأثر المحاسبي المباشر فوراً دون طلب API.')}/><div className="mt-6"><CurrentPriceWarning/></div><div className="mt-6 flex items-center gap-3"><strong>{c('Risque du scénario','مخاطر السيناريو')}</strong>{risk?<Badge tone={risk==='critical'?'danger':risk==='high'?'warning':risk==='low'?'good':'neutral'}>{c(({low:'Faible',moderate:'Modéré',high:'Élevé',critical:'Critique'} as Record<string,string>)[risk],({low:'منخفض',moderate:'متوسط',high:'مرتفع',critical:'حرج'} as Record<string,string>)[risk])}</Badge>:<span>—</span>}</div><section className="mt-6 grid gap-6 lg:grid-cols-[0.9fr_1.35fr_0.9fr]" data-testid="cockpit-grid"><Panel title={c('Construire le scénario','بناء السيناريو')}><ScenarioForm years={loaded!.years} sectors={loaded!.sectors} year={year} sectorCode={sectorCode} shockPercent={shockPercent} presets={presets} onYear={setYear} onSector={setSectorCode} onShock={setShockPercent} onPreset={choosePreset} onAdvanced={()=>void advanced()} onReset={reset} advancedBusy={planBusy}/></Panel><Panel title={c('Cascade de l’impact sur le PIB','شلال الأثر على الناتج')}>{calculation.result?<GdpShockWaterfallChart baselineGdp={baseline!} directLoss={calculation.result.directLoss} simulatedGdp={calculation.result.simulatedGdp}/>:<StatePanel state="empty" title={c('Valeur manquante','قيمة مفقودة')} description={calculation.error}/>}<Metadata/></Panel><section className="rounded-2xl border border-orange-200 bg-gradient-to-br from-white to-orange-50 p-5 shadow-lg"><p className="text-xs font-black uppercase tracking-widest text-orange-700">{c('Impact direct sur le PIB','الأثر المباشر على الناتج')}</p><p className="mt-2 text-5xl font-black tabular-nums">{calculation.result?`${calculation.result.directImpactPercentage.toFixed(2)}%`:'—'}</p><div className="mt-5 grid gap-3"><KpiCard label={c('Perte directe','الخسارة المباشرة')} value={calculation.result?.directLoss.toLocaleString()??'—'}/><KpiCard label={c('PIB simulé','الناتج المحاكى')} value={calculation.result?.simulatedGdp.toLocaleString()??'—'}/></div><div className="mt-4 grid grid-cols-2 gap-3"><KpiCard label={c('Valeur du secteur','قيمة القطاع')} value={sectorValue?.toLocaleString()??'—'}/><KpiCard label={c('Part du PIB','حصة الناتج')} value={sectorValue!=null&&baseline?`${(sectorValue/baseline*100).toFixed(2)}%`:'—'}/><KpiCard label={c('Secteur restant','القطاع المتبقي')} value={calculation.result?.remainingSectorValue.toLocaleString()??'—'}/><KpiCard label={c('Volatilité historique','التقلب التاريخي')} value={vol==null?'—':`${vol.toFixed(2)}%`}/></div></section></section>
 <section className="mt-6 grid gap-6 lg:grid-cols-2"><Panel title={c('Composition du PIB avant et après','تركيب الناتج قبل وبعد')}>{calculation.result?<GdpBeforeAfterChart baselineGdp={baseline!} sectorValue={sectorValue!} directLoss={calculation.result.directLoss}/>:<StatePanel state="empty" title={c('Données manquantes','بيانات مفقودة')} description={calculation.error}/>}<Metadata/></Panel><Panel title={c('Résumé de vulnérabilité','ملخص الهشاشة')}><p className="text-sm leading-7">{c(`Le secteur ${selected?.name_fr??sectorCode} représente ${sectorValue!=null&&baseline?(sectorValue/baseline*100).toFixed(2):'—'}% du PIB d’activité pour ${year}. Le choc réduit sa valeur restante sans modéliser les effets indirects.`,`يمثل قطاع ${selected?.name_ar??sectorCode} نسبة ${sectorValue!=null&&baseline?(sectorValue/baseline*100).toFixed(2):'—'}٪ من ناتج الأنشطة في ${year}. تخفض الصدمة قيمته المتبقية دون نمذجة الآثار غير المباشرة.`)}</p><div className="mt-4"><WarningBanner title={c('Impact comptable direct','أثر محاسبي مباشر')}>{c('Cette simulation représente un impact comptable direct et ne mesure pas automatiquement les effets indirects.','تمثل هذه المحاكاة أثراً محاسبياً مباشراً، ولا تقيس تلقائياً الآثار غير المباشرة.')}</WarningBanner></div></Panel></section>
 <Panel className="mt-6" title={c('Composition historique relative du PIB','التركيب النسبي التاريخي للناتج المحلي')} subtitle={c('Parts relatives à 100%; ce graphique ne montre pas la perte absolue du PIB.','حصص نسبية إلى 100٪؛ لا يعرض هذا الرسم خسارة الناتج المطلقة.')}><GdpCompositionChart data={loaded!.composition} selectedSector={sectorCode} selectedYear={year} onSelect={setSectorCode}/><div className="mt-3 flex flex-wrap gap-2">{['primary_sector','extractive_activities','manufacturing','construction_public_works','tertiary_sector'].map(code=>{const indicator=loaded!.sectors.find(i=>i.code===code);return <button data-testid={`composition-select-${code}`} type="button" onClick={()=>setSectorCode(code)} className={`rounded-full px-3 py-1 text-xs ${sectorCode===code?'bg-mauritania-700 text-white':'bg-slate-100'}`} key={code}>{indicator?c(indicator.name_fr,indicator.name_ar??indicator.name_fr):code}</button>})}</div><Metadata/></Panel>
 <section className="mt-6 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-black">{c('Aperçu du plan de réponse','معاينة خطة الاستجابة')}</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{Object.entries(previewActions).map(([horizon,text])=>{const priority=previewPriority(horizon,risk);return <article className="rounded-xl bg-slate-50 p-4" key={horizon}><div className="flex items-center justify-between gap-2"><p className="text-xs font-black uppercase text-mauritania-700">{c(({immediate:'0–3 mois',stabilization:'3–12 mois',recovery:'1–3 ans',structural:'Plus de 3 ans'} as Record<string,string>)[horizon],({immediate:'0–3 أشهر',stabilization:'3–12 شهراً',recovery:'1–3 سنوات',structural:'أكثر من 3 سنوات'} as Record<string,string>)[horizon])}</p><Badge tone={priority==='critical'?'danger':priority==='high'?'warning':'neutral'}>{c(({low:'Faible',moderate:'Modérée',high:'Élevée',critical:'Critique',medium:'Moyenne'} as Record<string,string>)[priority],({low:'منخفضة',moderate:'متوسطة',high:'عالية',critical:'حرجة',medium:'متوسطة'} as Record<string,string>)[priority])}</Badge></div><p className="mt-2 text-xs font-semibold text-slate-500">{selected?c(selected.name_fr,selected.name_ar??selected.name_fr):sectorCode}</p><p className="mt-2 text-sm leading-6">{c(text[0],text[1])}</p></article>})}</div>{planError&&<div className="mt-4"><WarningBanner title={c('Plan détaillé indisponible','الخطة المفصلة غير متاحة')}>{planError}</WarningBanner></div>}{plan&&<div className="mt-6"><ResponseTimeline recommendations={plan.recommendations}/></div>}</section><details className="mt-6 rounded-2xl border bg-white p-5"><summary className="cursor-pointer font-bold">{c('Méthodologie détaillée','المنهجية المفصلة')}</summary><p className="mt-3 text-sm leading-7">directLoss = sectorValue × shockRate; simulatedGdp = baselineGdp − directLoss; directImpactPercentage = directLoss / baselineGdp × 100. {c('PIB selon l’approche par activité uniquement.','يستخدم الناتج حسب منهج الأنشطة فقط.')}</p></details></PageContainer>}
