import { useEffect, useMemo, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { GdpCompositionChart } from '../components/charts/GdpCompositionChart'
import { GdpShockWaterfallChart } from '../components/charts/GdpShockWaterfallChart'
import { GdpScenarioComparisonChart } from '../components/charts/GdpScenarioComparisonChart'
import { CompensationSectorChart, type CompensationChartRow } from '../components/charts/CompensationSectorChart'
import { ResponseTimeline } from '../components/recommendations/ResponseTimeline'
import { TargetSectorSelector } from '../components/simulation/TargetSectorSelector'
import { Badge, CurrentPriceWarning, DataTable, Metadata, SelectField, useCopy } from '../components/DataDisplay'
import { KpiCard, PageContainer, PageHeader, Panel, StatePanel, WarningBanner } from '../components/Page'
import { useLanguage } from '../contexts/LanguageContext'
import { generateRecommendations } from '../services/recommendations'
import { loadSimulationPageData } from '../services/stressTest'
import type { Indicator, RecommendationResponse } from '../types/economic'
import { accountingFeasibility, calculateRequiredCompensationGrowth, calculateSectorShock, hasHierarchyOverlap, historicalEvidence, resilienceRanking, scenarioRisk, targetConflict } from '../utils/simulation'
import { ButtonSpinner, PageLoadingState } from '../components/LoadingStates'
import { SectionErrorState } from '../components/ErrorStates'

type PageData=Awaited<ReturnType<typeof loadSimulationPageData>>
type CompensationMode='individual'|'shared'
const presets=[
 {code:'extractive_stop',fr:'Arrêt extractif complet',ar:'توقف الاستخراج كلياً',affected:'extractive_activities',shock:100},
 {code:'fishing_half',fr:'Pêche −50%',ar:'الصيد −50٪',affected:'fishing',shock:50},
 {code:'construction_thirty',fr:'BTP −30%',ar:'البناء −30٪',affected:'construction_public_works',shock:30},
 {code:'commerce_quarter',fr:'Commerce −25%',ar:'التجارة −25٪',affected:'commerce',shock:25},
]
const compositionCodes=['primary_sector','extractive_activities','manufacturing','construction_public_works','tertiary_sector']

function equalAllocations(codes:string[]){if(!codes.length)return{};const base=Math.floor(10000/codes.length)/100;const result=Object.fromEntries(codes.map(code=>[code,base])) as Record<string,number>;result[codes.at(-1)!]=100-base*(codes.length-1);return result}
function queryTargets(search:URLSearchParams){return (search.get('targets')??'').split(',').filter(Boolean).slice(0,4)}
function safeNumber(value:string|null,fallback:number){if(value==null||value.trim()==='')return fallback;const parsed=Number(value);return Number.isFinite(parsed)?parsed:fallback}

function ScenarioSentence({year,affected,shock,target,sectors,years,onYear,onAffected,onShock,onTarget}:{year:number;affected:string;shock:number;target:string;sectors:Indicator[];years:number[];onYear:(value:number)=>void;onAffected:(value:string)=>void;onShock:(value:number)=>void;onTarget:(value:string)=>void}){
 const c=useCopy();const control='mx-1 min-h-11 max-w-full rounded-lg border border-mauritania-300 bg-white px-2 py-1 font-bold text-mauritania-800'
 return <p data-testid="interactive-scenario-sentence" className="text-lg font-bold leading-[3.25rem]">{c('En','في سنة')} <select aria-label={c('Année dans le scénario','السنة في السيناريو')} value={year} onChange={event=>onYear(+event.target.value)} className={control}>{[...years].reverse().map(value=><option key={value}>{value}</option>)}</select>{c(', que se passerait-il si', '، ماذا سيحدث إذا انخفض')} <select aria-label={c('Secteur touché dans le scénario','القطاع المتأثر في السيناريو')} value={affected} onChange={event=>onAffected(event.target.value)} className={control}>{sectors.map(item=><option value={item.code} key={item.code}>{c(item.name_fr,item.name_ar??item.name_fr)}</option>)}</select> {c('diminuait de','بنسبة')} <input aria-label={c('Choc dans le scénario','نسبة الصدمة في السيناريو')} type="number" min="0" max="100" value={shock} onChange={event=>onShock(Math.min(100,Math.max(0,+event.target.value)))} className={`${control} w-24 tabular-nums`}/>% {c('et si','، وكان على')} <select aria-label={c('Secteur cible dans le scénario','القطاع المستهدف في السيناريو')} value={target} onChange={event=>onTarget(event.target.value)} className={control}>{sectors.filter(item=>!hasHierarchyOverlap(affected,item.code)).map(item=><option value={item.code} key={item.code}>{c(item.name_fr,item.name_ar??item.name_fr)}</option>)}</select> {c('devait compenser cette perte ?','تعويض هذه الخسارة؟')}</p>
}

export function SimulationAndReactionPage(){
 const c=useCopy();const {language}=useLanguage();const [search,setSearch]=useSearchParams()
 const initialAffected=search.get('affected')||search.get('sector')||'extractive_activities';const initialAffectedRef=useRef(initialAffected);const initialTargets=queryTargets(search)
 const [loaded,setLoaded]=useState<PageData|null>(null),[initialError,setInitialError]=useState('')
 const [year,setYearState]=useState(safeNumber(search.get('year'),2024)),[affected,setAffectedState]=useState(initialAffected),[shock,setShockState]=useState(Math.min(100,Math.max(0,safeNumber(search.get('shock'),50))))
 const [targets,setTargetsState]=useState(initialTargets.length?initialTargets:['construction_public_works']),[mode,setMode]=useState<CompensationMode>((search.get('mode')==='shared'?'shared':'individual'))
 const [allocations,setAllocations]=useState<Record<string,number>>(()=>equalAllocations(initialTargets.length?initialTargets:['construction_public_works']))
 const [sectorQuery,setSectorQuery]=useState(''),[plan,setPlan]=useState<RecommendationResponse|null>(null),[planBusy,setPlanBusy]=useState(false),[planError,setPlanError]=useState('')

 const writeUrl=(next:{year?:number;affected?:string;shock?:number;targets?:string[];mode?:CompensationMode},replace=false)=>{const params=new URLSearchParams(search);if(next.year!=null)params.set('year',String(next.year));if(next.affected)params.set('affected',next.affected);params.delete('sector');if(next.shock!=null)params.set('shock',String(next.shock));if(next.targets)params.set('targets',next.targets.join(','));if(next.mode)params.set('mode',next.mode);setSearch(params,{replace})}
 const setYear=(value:number)=>{setYearState(value);writeUrl({year:value})}
 const setShock=(value:number)=>{const safe=Math.min(100,Math.max(0,value));setShockState(safe);writeUrl({shock:safe},true)}
 const setTargetCodes=(codes:string[])=>{setTargetsState(codes);setAllocations(equalAllocations(codes));writeUrl({targets:codes})}
 const setAffected=(value:string)=>{const compatible=targets.filter(code=>!hasHierarchyOverlap(value,code));const fallback=loaded?.sectors.find(item=>!hasHierarchyOverlap(value,item.code))?.code;const nextTargets=compatible.length?compatible:fallback?[fallback]:[];setAffectedState(value);setTargetsState(nextTargets);setAllocations(equalAllocations(nextTargets));writeUrl({affected:value,targets:nextTargets})}
 const setCompensationMode=(value:CompensationMode)=>{setMode(value);writeUrl({mode:value})}

 useEffect(()=>{let active=true;void loadSimulationPageData().then(result=>{if(!active)return;setLoaded(result);const latest=result.years.at(-1)??2024,initialAffectedCode=initialAffectedRef.current;setYearState(current=>result.years.includes(current)?current:latest);setAffectedState(current=>result.sectors.some(item=>item.code===current)?current:'extractive_activities');setTargetsState(current=>{const valid=current.filter(code=>result.sectors.some(item=>item.code===code)&&!hasHierarchyOverlap(initialAffectedCode,code));const next=valid.length?valid:[result.sectors.find(item=>item.code==='construction_public_works'&&!hasHierarchyOverlap(initialAffectedCode,item.code))?.code??result.sectors.find(item=>!hasHierarchyOverlap(initialAffectedCode,item.code))?.code].filter(Boolean) as string[];setAllocations(equalAllocations(next));return next})}).catch(reason=>active&&setInitialError(reason instanceof Error?reason.message:String(reason)));return()=>{active=false}},[])
 useEffect(()=>{const urlYear=safeNumber(search.get('year'),year),urlAffected=search.get('affected')||search.get('sector'),urlShock=safeNumber(search.get('shock'),shock),urlTargets=queryTargets(search),urlMode=search.get('mode');if(loaded?.years.includes(urlYear))setYearState(urlYear);if(urlAffected&&loaded?.sectors.some(item=>item.code===urlAffected))setAffectedState(urlAffected);if(urlShock>=0&&urlShock<=100)setShockState(urlShock);if(urlTargets.length&&urlTargets.join(',')!==targets.join(',')){const valid=urlTargets.filter(code=>loaded?.sectors.some(item=>item.code===code)&&!hasHierarchyOverlap(urlAffected??affected,code));if(valid.length){setTargetsState(valid);setAllocations(equalAllocations(valid))}}if(urlMode==='shared'||urlMode==='individual')setMode(urlMode)},[affected,loaded,search,shock,targets,year])

 const baseline=loaded?.gdpSeries.find(point=>point.year===year)?.value??null;const affectedValue=loaded?.seriesByCode[affected]?.find(point=>point.year===year)?.value??null
 const direct=useMemo(()=>{try{return {value:calculateSectorShock({baselineGdp:baseline,affectedSectorValue:affectedValue,shockRate:shock/100}),error:''}}catch(reason){return {value:null,error:reason instanceof Error?reason.message:String(reason)}}},[affectedValue,baseline,shock])
 const allocationTotal=targets.reduce((sum,code)=>sum+(allocations[code]??0),0);const allocationValid=mode==='individual'||Math.abs(allocationTotal-100)<=0.01
 const compensationRows=useMemo(()=>targets.flatMap(code=>{const targetValue=loaded?.seriesByCode[code]?.find(point=>point.year===year)?.value??null;if(!direct.value||!allocationValid)return[];const allocatedLoss=mode==='shared'?direct.value.directLoss*(allocations[code]??0)/100:direct.value.directLoss;try{const result=calculateRequiredCompensationGrowth({directLoss:allocatedLoss,targetSectorValue:targetValue});const evidence=historicalEvidence(loaded?.seriesByCode[code]??[]);const item=loaded?.sectors.find(sector=>sector.code===code);return [{code,name:c(item?.name_fr??code,item?.name_ar??item?.name_fr??code),targetValue:result.targetSectorValue,allocatedLoss,requiredAdditionalValue:result.requiredAdditionalValue,requiredGrowth:result.requiredGrowthPercentage,targetValueAfter:result.targetValueAfterCompensation,evidence,feasibility:accountingFeasibility(result.requiredGrowthPercentage)}]}catch{return[]}}),[allocationValid,allocations,c,direct.value,loaded,mode,targets,year])
 const risk=direct.value?scenarioRisk(direct.value.directImpactPercentage):null;const selectedAffected=loaded?.sectors.find(item=>item.code===affected);const primaryCompensation=compensationRows[0]
 const compensationGain=mode==='shared'&&allocationValid?compensationRows.reduce((sum,row)=>sum+row.requiredAdditionalValue,0):primaryCompensation?.requiredAdditionalValue??0
 const targetExistingValue=mode==='shared'?compensationRows.reduce((sum,row)=>sum+row.targetValue,0):primaryCompensation?.targetValue??0
 const ranking=useMemo(()=>direct.value&&loaded?resilienceRanking(loaded.sectors.map(item=>({code:item.code,sectorValue:loaded.seriesByCode[item.code]?.find(point=>point.year===year)?.value??null,baselineGdp:baseline,directLoss:direct.value!.directLoss,points:loaded.seriesByCode[item.code]??[],hierarchyConflict:hasHierarchyOverlap(affected,item.code)}))).filter(row=>!row.hierarchyConflict&&row.requiredGrowth!=null):[],[affected,baseline,direct.value,loaded,year])
 const nf=new Intl.NumberFormat(language==='ar'?'ar-MR':'fr-MR',{maximumFractionDigits:2});const fmt=(value:number|null|undefined,sign=false)=>value==null?'—':`${sign&&value>0?'+':''}${nf.format(value)}`
 const feasibilityCopy=(level:string)=>({attainable:c('relativement atteignable sur le plan comptable','قابل للتحقق نسبياً من منظور محاسبي'),demanding:c('exigeante','متطلبة'), 'highly-demanding':c('très exigeante','شديدة المتطلبات'),'very-difficult':c('très difficile','صعبة جداً'),extreme:c('une exigence comptable extrême','متطلب محاسبي بالغ')})[level]??level
 const confidenceCopy=(confidence:string)=>({high:c('élevée','عالية'),medium:c('moyenne','متوسطة'),low:c('faible','منخفضة')})[confidence]??confidence
 const applyPreset=(code:string)=>{const preset=presets.find(item=>item.code===code);if(!preset)return;const compatible=targets.filter(target=>!hasHierarchyOverlap(preset.affected,target));const nextTargets=compatible.length?compatible:['construction_public_works'].filter(target=>!hasHierarchyOverlap(preset.affected,target));setAffectedState(preset.affected);setShockState(preset.shock);setTargetsState(nextTargets);setAllocations(equalAllocations(nextTargets));writeUrl({affected:preset.affected,shock:preset.shock,targets:nextTargets})}
 const reset=()=>{const next=['construction_public_works'];setYearState(2024);setAffectedState('extractive_activities');setShockState(50);setTargetsState(next);setAllocations(equalAllocations(next));setMode('individual');setPlan(null);writeUrl({year:2024,affected:'extractive_activities',shock:50,targets:next,mode:'individual'})}
 const requestPlan=async()=>{setPlanBusy(true);setPlanError('');try{setPlan(await generateRecommendations(year,affected,shock,'one_year'))}catch{setPlanError(c('Le plan détaillé du serveur est indisponible.','خطة الخادم المفصلة غير متاحة.'))}finally{setPlanBusy(false)}}

 if(!loaded&&!initialError)return <PageLoadingState/>;if(initialError)return <PageContainer><SectionErrorState details={initialError} onRetry={()=>window.location.reload()}/></PageContainer>
 const filteredAffected=loaded!.sectors.filter(item=>`${item.name_fr} ${item.name_ar??''} ${item.code}`.toLowerCase().includes(sectorQuery.toLowerCase()))
 const chartRows:CompensationChartRow[]=compensationRows.map(row=>({code:row.code,name:row.name,currentValue:row.targetValue,requiredAdditionalValue:row.requiredAdditionalValue,requiredGrowth:row.requiredGrowth,historicalAverage:row.evidence.averageGrowth,historicalMaximum:row.evidence.maximumGrowth,volatility:row.evidence.volatility,completeness:row.evidence.completeness}))
 const responseStages=[
  {horizon:c('Réponse immédiate · 0–3 mois','الاستجابة الفورية · 0–3 أشهر'),action:c(`Protéger la continuité opérationnelle de ${selectedAffected?.name_fr??affected} et vérifier la perte comptable observée.`,`حماية استمرارية عمليات ${selectedAffected?.name_ar??affected} والتحقق من الخسارة المحاسبية المرصودة.`),actor:c('Ministère sectoriel, opérateurs, statistique nationale','الوزارة القطاعية والمشغلون والإحصاء الوطني'),evidence:c(`Perte directe simulée : ${fmt(direct.value?.directLoss)} millions MRU.`,`الخسارة المباشرة المحاكاة: ${fmt(direct.value?.directLoss)} مليون أوقية.`),objective:c('Limiter la désorganisation immédiate et confirmer les données.','الحد من الاضطراب الفوري وتأكيد البيانات.')},
  {horizon:c('Stabilisation · 3–12 mois','الاستقرار · 3–12 شهراً'),action:c(`Auditer la capacité inutilisée des ${targets.length} secteur(s) cible(s) avant toute mobilisation.`,`تدقيق الطاقة غير المستغلة في ${targets.length} من القطاعات المستهدفة قبل تعبئتها.`),actor:c('Ministères économiques, entreprises, banques','الوزارات الاقتصادية والشركات والبنوك'),evidence:c(`Croissance comptable requise minimale parmi les cibles : ${fmt(compensationRows.length?Math.min(...compensationRows.map(row=>row.requiredGrowth)):null,true)}%.`,`أدنى نمو محاسبي مطلوب بين القطاعات المستهدفة: ${fmt(compensationRows.length?Math.min(...compensationRows.map(row=>row.requiredGrowth)):null,true)}٪.`),objective:c('Tester les contraintes de capacité, de financement et d’approvisionnement.','اختبار قيود الطاقة والتمويل والإمداد.')},
  {horizon:c('Reprise · 1–3 ans','التعافي · 1–3 سنوات'),action:c('Programmer des gains de productivité graduels dans les secteurs cibles dont les données sont les plus complètes.','برمجة مكاسب إنتاجية تدريجية في القطاعات المستهدفة ذات البيانات الأكثر اكتمالاً.'),actor:c('Secteur privé, agences d’investissement, formation','القطاع الخاص ووكالات الاستثمار والتكوين'),evidence:c(`Risque du scénario : ${risk??'—'}; la comparaison reste nominale et historique.`,`مخاطر السيناريو: ${risk??'—'}؛ وتبقى المقارنة اسمية وتاريخية.`),objective:c('Renforcer la capacité productive sans supposer une compensation instantanée.','تعزيز القدرة الإنتاجية دون افتراض تعويض فوري.')},
  {horizon:c('Résilience structurelle · plus de 3 ans','المرونة الهيكلية · أكثر من 3 سنوات'),action:c('Diversifier les branches sans additionner parents et enfants, et suivre la concentration du PIB.','تنويع الفروع دون جمع الأصل والفروع ومتابعة تركز الناتج.'),actor:c('Planification, finances, statistique, régulateurs','التخطيط والمالية والإحصاء والجهات التنظيمية'),evidence:c(`Part du secteur touché : ${affectedValue!=null&&baseline?fmt(affectedValue/baseline*100):'—'}% du PIB d’activité.`,`حصة القطاع المتأثر: ${affectedValue!=null&&baseline?fmt(affectedValue/baseline*100):'—'}٪ من ناتج الأنشطة.`),objective:c('Réduire durablement l’exposition aux chocs sectoriels.','خفض التعرض للصدمات القطاعية بصورة مستدامة.')},
 ]

 return <PageContainer>
  <PageHeader eyebrow={c('Cockpit de scénario économique','قمرة السيناريو الاقتصادي')} title={c('Et si un secteur s’arrêtait demain ?','ماذا لو توقف أحد القطاعات غداً؟')} description={c('Simuler un choc, mesurer la perte et identifier les secteurs capables de renforcer la résilience économique.','محاكاة الصدمة وقياس الخسارة وتحديد القطاعات القادرة على تعزيز المرونة الاقتصادية.')}/>
  <Panel className="mt-6 border-mauritania-200 bg-mauritania-50/40" title={c('Scénario réactif','سيناريو تفاعلي')}><ScenarioSentence year={year} affected={affected} shock={shock} target={targets[0]??''} sectors={loaded!.sectors} years={loaded!.years} onYear={setYear} onAffected={setAffected} onShock={setShock} onTarget={value=>setTargetCodes([value,...targets.filter(code=>code!==value)].slice(0,4))}/><div className="mt-4 flex flex-wrap gap-2">{presets.map(item=><button type="button" onClick={()=>applyPreset(item.code)} className="min-h-11 rounded-full border bg-white px-4 py-2 text-sm font-bold" key={item.code}>{c(item.fr,item.ar)}</button>)}</div></Panel>
  <div className="mt-6"><CurrentPriceWarning/></div>
  <div className="mt-5 flex items-center gap-3"><strong>{c('Niveau de risque','مستوى المخاطر')}</strong>{risk?<Badge tone={risk==='critical'?'danger':risk==='high'?'warning':risk==='low'?'good':'neutral'}>{c(({low:'Faible',moderate:'Modéré',high:'Élevé',critical:'Critique'} as Record<string,string>)[risk],({low:'منخفض',moderate:'متوسط',high:'مرتفع',critical:'حرج'} as Record<string,string>)[risk])}</Badge>:<span>—</span>}</div>

  <section className="mt-6 grid gap-6 lg:grid-cols-[0.9fr_1.35fr_0.9fr]" data-testid="cockpit-grid">
   <Panel className="order-1" title={c('Secteur touché et choc','القطاع المتأثر والصدمة')}><div className="grid gap-5"><SelectField label={c('Année de référence','السنة المرجعية')} value={year} onChange={value=>setYear(+value)} testId="simulation-year">{[...loaded!.years].reverse().map(value=><option key={value}>{value}</option>)}</SelectField><label className="grid gap-1 text-sm font-semibold"><span>{c('Rechercher le secteur touché','البحث عن القطاع المتأثر')}</span><input value={sectorQuery} onChange={event=>setSectorQuery(event.target.value)} className="min-h-11 min-w-0 rounded-xl border px-3 py-2.5"/></label><SelectField label={c('Secteur touché','القطاع المتأثر')} value={affected} onChange={setAffected} testId="simulation-sector">{filteredAffected.map(item=><option value={item.code} key={item.code}>{c(item.name_fr,item.name_ar??item.name_fr)}</option>)}</SelectField><label className="grid gap-3 text-sm font-semibold"><span className="flex justify-between gap-3"><span>{c('Intensité du choc','شدة الصدمة')}</span><output htmlFor="shock-slider" className="tabular-nums">{shock}%</output></span><div className="relative pt-7"><output aria-hidden="true" className="absolute top-0 -translate-x-1/2 rounded bg-navy-900 px-2 py-1 text-xs text-white rtl:translate-x-1/2" style={{insetInlineStart:`${shock}%`}}>{shock}%</output><input id="shock-slider" data-testid="shock-slider" type="range" min="0" max="100" value={shock} aria-valuetext={c(`${shock} pour cent`,`نسبة ${shock} بالمئة`)} onChange={event=>setShock(+event.target.value)} onKeyDown={event=>{if(event.key==='Home'){event.preventDefault();setShock(0)}if(event.key==='End'){event.preventDefault();setShock(100)}}} className="h-11 w-full accent-orange-600"/></div></label><label className="grid gap-1 text-sm font-semibold"><span>{c('Pourcentage exact','النسبة الدقيقة')}</span><input aria-label={c('Pourcentage exact du choc','النسبة الدقيقة للصدمة')} type="number" min="0" max="100" value={shock} onChange={event=>setShock(+event.target.value)} className="min-h-11 min-w-0 rounded-xl border px-3 py-2.5 tabular-nums"/></label><div className="flex flex-wrap gap-2">{[10,25,50,75,100].map(value=><button type="button" onClick={()=>setShock(value)} className={`min-h-11 rounded-full px-4 py-2 text-sm font-bold ${shock===value?'bg-gold-400':'bg-slate-100'}`} key={value}>{value}%</button>)}</div><button type="button" onClick={reset} className="min-h-11 rounded-xl border px-4 py-3 font-bold">{c('Réinitialiser','إعادة تعيين')}</button></div></Panel>
   <Panel className="order-3 lg:order-2" title={c('Cascade du choc et de la compensation','شلال الصدمة والتعويض')}>{direct.value?<GdpShockWaterfallChart baselineGdp={baseline!} directLoss={direct.value.directLoss} simulatedGdp={direct.value.simulatedGdp} compensationGain={compensationGain}/>:<StatePanel state="empty" title={c('Valeur manquante','قيمة مفقودة')} description={c('Choisissez une autre année ou un autre secteur.','اختر سنة أو قطاعاً آخر.')}/>}<Metadata/></Panel>
   <section className="order-2 rounded-3xl border border-orange-200 bg-gradient-to-br from-white to-orange-50 p-5 shadow-lg lg:order-3"><p className="text-xs font-black uppercase tracking-widest text-orange-700">{c('Impact direct dominant','الأثر المباشر الرئيسي')}</p><p className="mt-2 text-5xl font-black tabular-nums">{direct.value?`${fmt(direct.value.directImpactPercentage)}%`:'—'}</p><div className="mt-5 grid gap-3"><KpiCard label={c('PIB avant choc','الناتج قبل الصدمة')} value={fmt(baseline)}/><KpiCard label={c('Perte directe','الخسارة المباشرة')} value={direct.value?`−${fmt(direct.value.directLoss)}`:'—'}/><KpiCard label={c('PIB après choc','الناتج بعد الصدمة')} value={fmt(direct.value?.simulatedGdp)}/><KpiCard label={c('Valeur restante du secteur','القيمة المتبقية للقطاع')} value={fmt(direct.value?.affectedSectorRemainingValue)}/></div>{primaryCompensation&&<div className="mt-4 rounded-2xl bg-white p-4"><p className="text-sm font-bold">{c(`Croissance requise de ${primaryCompensation.name}`,`النمو المطلوب في ${primaryCompensation.name}`)}</p><p className="mt-1 text-3xl font-black text-mauritania-700">+{fmt(primaryCompensation.requiredGrowth)}%</p><p className="mt-2 text-xs text-slate-500">{c('Exigence comptable expérimentale, pas une prévision.','متطلب محاسبي تجريبي وليس توقعاً.')}</p></div>}</section>
  </section>

  <section className="mt-6 grid gap-6 xl:grid-cols-[0.9fr_1.1fr]">
   <Panel title={c('Secteurs de compensation','قطاعات التعويض')}><TargetSectorSelector sectors={loaded!.sectors} affected={affected} targets={targets} onChange={setTargetCodes}/><div className="mt-5 flex flex-wrap gap-2" role="radiogroup" aria-label={c('Mode de compensation','وضع التعويض')}>{(['individual','shared'] as CompensationMode[]).map(value=><button role="radio" aria-checked={mode===value} type="button" onClick={()=>setCompensationMode(value)} className={`min-h-11 rounded-full px-4 py-2 font-bold ${mode===value?'bg-mauritania-700 text-white':'bg-slate-100'}`} key={value}>{value==='individual'?c('Comparaison individuelle','مقارنة فردية'):c('Compensation partagée','تعويض مشترك')}</button>)}</div>{mode==='shared'&&<div className="mt-4 grid gap-3">{targets.map(code=>{const item=loaded!.sectors.find(sector=>sector.code===code);return <label className="flex items-center justify-between gap-3 text-sm font-semibold" key={code}><span>{c(item?.name_fr??code,item?.name_ar??item?.name_fr??code)}</span><span className="flex items-center gap-1"><input aria-label={c(`Allocation de ${item?.name_fr??code}`,`تخصيص ${item?.name_ar??code}`)} type="number" min="0" max="100" step="0.01" value={allocations[code]??0} onChange={event=>setAllocations(old=>({...old,[code]:+event.target.value}))} className="min-h-11 w-28 rounded-xl border px-3 tabular-nums"/>%</span></label>})}<p role="status" className={`font-bold ${allocationValid?'text-mauritania-700':'text-red-700'}`}>{c('Total','المجموع')}: {fmt(allocationTotal)}% {allocationValid?'✓':c('— doit être égal à 100%','— يجب أن يساوي 100٪')}</p></div>}</Panel>
   <Panel title={c('Croissance comptable requise','النمو المحاسبي المطلوب')}>{compensationRows.length?<div className="grid gap-4 sm:grid-cols-2">{compensationRows.map(row=><article className="rounded-2xl border p-4" key={row.code}><h3 className="font-black">{row.name}</h3><p className="mt-2 text-3xl font-black text-orange-700">+{fmt(row.requiredGrowth)}%</p><p className="mt-2 text-sm">{c('Valeur actuelle','القيمة الحالية')}: {fmt(row.targetValue)} · {c('Hausse requise','الزيادة المطلوبة')}: {fmt(row.requiredAdditionalValue)}</p><p className="mt-2 text-sm">{c('Moyenne nominale historique','المتوسط الاسمي التاريخي')}: {fmt(row.evidence.averageGrowth,true)}% · {c('Maximum','الحد الأقصى')}: {fmt(row.evidence.maximumGrowth,true)}% · {c('Dernière croissance','أحدث نمو')}: {fmt(row.evidence.latestGrowth,true)}%</p><p className="mt-2 text-sm">{c('Volatilité','التقلب')}: {fmt(row.evidence.volatility)}% · {c('Complétude','الاكتمال')}: {fmt(row.evidence.completeness)}%</p><div className="mt-3"><Badge tone={row.feasibility==='attainable'?'good':row.feasibility==='demanding'?'neutral':'warning'}>{feasibilityCopy(row.feasibility)}</Badge></div><p className="mt-3 text-sm leading-6">{c(`La compensation exigerait ${fmt(row.requiredGrowth)}% de croissance de ${row.name}. Cette exigence est ${feasibilityCopy(row.feasibility)} et doit être comparée avec une moyenne historique de ${fmt(row.evidence.averageGrowth)}%.`,`يتطلب التعويض نمواً بنسبة ${fmt(row.requiredGrowth)}٪ في ${row.name}. هذا المتطلب ${feasibilityCopy(row.feasibility)} ويجب مقارنته بمتوسط تاريخي قدره ${fmt(row.evidence.averageGrowth)}٪.`)}</p></article>)}</div>:<StatePanel state="empty" title={allocationValid?c('Donnée cible indisponible','بيانات القطاع المستهدف غير متاحة'):c('Allocation invalide','تخصيص غير صالح')} description={allocationValid?c('Choisissez un secteur cible ayant une valeur positive pour cette année.','اختر قطاعاً مستهدفاً له قيمة موجبة في هذه السنة.'):c('Ajustez les parts pour obtenir exactement 100%.','عدّل الحصص للحصول على 100٪ تماماً.')}/>}</Panel>
  </section>

  <Panel className="mt-6" title={c('Comparaison des secteurs cibles','مقارنة القطاعات المستهدفة')} subtitle={c('Classés ici du besoin de croissance le plus faible au plus élevé, sans désigner automatiquement une meilleure option.','مرتبة هنا من أدنى نمو مطلوب إلى أعلاه دون تعيين خيار أفضل تلقائياً.')}>{chartRows.length?<CompensationSectorChart rows={chartRows}/>:<StatePanel state="empty" title={c('Comparaison indisponible','المقارنة غير متاحة')} description={c('Sélectionnez au moins un secteur cible compatible.','اختر قطاعاً مستهدفاً متوافقاً واحداً على الأقل.')}/>}</Panel>

  <section className="mt-6 grid gap-6 xl:grid-cols-2">
   <Panel title={c('PIB avant, après et compensé','الناتج قبل الصدمة وبعدها وبعد التعويض')}>{direct.value&&primaryCompensation?<GdpScenarioComparisonChart unaffectedEconomyValue={direct.value.unaffectedEconomyValue} affectedSectorValue={affectedValue!} remainingAffectedValue={direct.value.affectedSectorRemainingValue} directLoss={direct.value.directLoss} targetExistingValue={targetExistingValue} compensationGain={compensationGain}/>:<StatePanel state="empty" title={c('Calcul non pris en charge','الحساب غير مدعوم')} description={c('Une valeur cible valide est nécessaire.','يلزم توفر قيمة صالحة للقطاع المستهدف.')}/>}<Metadata/></Panel>
   <Panel title={c('Composition historique relative du PIB','التركيب النسبي التاريخي للناتج المحلي')} subtitle={c('Ce graphique montre la composition relative du PIB, pas la perte économique absolue.','يعرض هذا الرسم التركيب النسبي للناتج، وليس الخسارة الاقتصادية المطلقة.')}><GdpCompositionChart data={loaded!.composition} selectedSector={affected} targetSectors={targets} selectedYear={year} onSelect={setAffected}/><div className="mt-3 grid gap-2 sm:grid-cols-2">{compositionCodes.map(code=>{const item=loaded!.sectors.find(sector=>sector.code===code);if(!item)return null;const conflict=targetConflict(affected,targets,code);return <div className="flex gap-2" key={code}><button data-testid={`composition-select-${code}`} type="button" onClick={()=>setAffected(code)} className={`min-h-11 flex-1 rounded-xl px-3 py-2 text-xs font-bold ${affected===code?'bg-orange-600 text-white':'bg-slate-100'}`}>{c(item.name_fr,item.name_ar??item.name_fr)}</button><button type="button" disabled={Boolean(conflict)||targets.length>=4} onClick={()=>setTargetCodes([...targets,code])} aria-label={c(`Ajouter ${item.name_fr} comme cible`,`إضافة ${item.name_ar??item.name_fr} كهدف`)} className="min-h-11 min-w-11 rounded-xl border font-black disabled:opacity-30">+</button></div>})}</div><Metadata/></Panel>
  </section>

  <Panel className="mt-6" title={c('Classement expérimental des secteurs de résilience','الترتيب التجريبي لقطاعات المرونة')} subtitle={c('Score: taille 20%, besoin de compensation 35%, tendance 15%, volatilité 10%, complétude 15%, compatibilité hiérarchique 5%.','الدرجة: الحجم 20٪، عبء التعويض 35٪، الاتجاه 15٪، التقلب 10٪، الاكتمال 15٪، التوافق الهرمي 5٪.')}><DataTable headers={[c('Rang','الرتبة'),c('Secteur','القطاع'),c('Croissance requise','النمو المطلوب'),c('Moyenne historique','المتوسط التاريخي'),c('Volatilité','التقلب'),c('Score','الدرجة'),c('Raison / confiance / limite','السبب / الثقة / القيد')]} rows={ranking.slice(0,10).map((row,index)=>{const item=loaded!.sectors.find(sector=>sector.code===row.code);return [index+1,c(item?.name_fr??row.code,item?.name_ar??item?.name_fr??row.code),row.requiredGrowth==null?'—':`${fmt(row.requiredGrowth)}%`,row.averageGrowth==null?'—':`${fmt(row.averageGrowth,true)}%`,row.volatility==null?'—':`${fmt(row.volatility)}%`,fmt(row.score),c(`Part du PIB ${fmt(row.gdpShare)}%, besoin comptable et complétude ${fmt(row.completeness)}%. Confiance ${confidenceCopy(row.confidence)}. Ne mesure ni rentabilité, emploi, coût d’investissement ni faisabilité régionale.`,`حصة الناتج ${fmt(row.gdpShare)}٪ والعبء المحاسبي والاكتمال ${fmt(row.completeness)}٪. الثقة ${confidenceCopy(row.confidence)}. لا تقيس الربحية أو العمالة أو تكلفة الاستثمار أو الجدوى الإقليمية.`)]})}/></Panel>

  <section className="mt-6 rounded-3xl border bg-white p-5 shadow-card sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">{c('Plan de réponse et de résilience','خطة الاستجابة والمرونة')}</h2><p className="mt-1 text-sm text-slate-500">{c('Actions distinctes par horizon, fondées sur le scénario courant.','إجراءات مختلفة حسب الأفق ومبنية على السيناريو الحالي.')}</p></div><button type="button" disabled={planBusy} onClick={()=>void requestPlan()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-mauritania-700 px-4 py-3 font-bold text-white disabled:opacity-50">{planBusy&&<ButtonSpinner/>}{planBusy?c('Génération…','جارٍ الإنشاء…'):c('Générer le plan détaillé','إنشاء الخطة المفصلة')}</button></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{responseStages.map((stage,index)=><article className="rounded-2xl border bg-slate-50 p-4" key={stage.horizon}><div className="flex items-start justify-between gap-2"><h3 className="font-black text-mauritania-800">{stage.horizon}</h3><Badge tone={index===0&&risk==='critical'?'danger':index<2?'warning':'neutral'}>{index===0?c('Immédiate','فورية'):index===1?c('Élevée','عالية'):c('Moyenne','متوسطة')}</Badge></div><p className="mt-3 text-sm font-semibold leading-6">{stage.action}</p><p className="mt-3 text-xs leading-5"><strong>{c('Preuve','الدليل')}:</strong> {stage.evidence}</p><p className="mt-2 text-xs leading-5"><strong>{c('Acteurs','الجهات')}:</strong> {stage.actor}</p><p className="mt-2 text-xs leading-5"><strong>{c('Étapes','الخطوات')}:</strong> {c('Valider les données, tester les contraintes, définir un responsable et suivre chaque trimestre.','التحقق من البيانات واختبار القيود وتحديد مسؤول والمتابعة كل ربع سنة.')}</p><p className="mt-2 text-xs leading-5"><strong>{c('Objectif','الهدف')}:</strong> {stage.objective}</p><p className="mt-2 text-xs leading-5"><strong>{c('À suivre','للمتابعة')}:</strong> {c('PIB sectoriel nominal, croissance, volatilité, complétude.','الناتج القطاعي الاسمي والنمو والتقلب والاكتمال.')}</p><p className="mt-2 text-xs text-slate-500">{c('Confiance limitée aux comptes nationaux; effets indirects non mesurés.','الثقة محدودة بالحسابات الوطنية؛ الآثار غير المباشرة غير مقاسة.')}</p></article>)}</div>{planError&&<div className="mt-4"><WarningBanner title={c('Plan détaillé indisponible','الخطة المفصلة غير متاحة')}>{planError}</WarningBanner></div>}{plan&&<div className="mt-6"><ResponseTimeline recommendations={plan.recommendations}/></div>}</section>

  <details className="mt-6 rounded-3xl border bg-white p-5"><summary className="min-h-11 cursor-pointer text-lg font-black">{c('À propos de la simulation','حول المحاكاة')}</summary><div className="mt-4 space-y-3 text-sm leading-7"><p>{c('MEIP simule en temps réel l’impact direct d’un choc sectoriel sur le PIB mauritanien. L’utilisateur choisit le secteur affecté, l’intensité du choc et un ou plusieurs secteurs à mobiliser pour compenser la perte.','تحاكي منصة MEIP في الوقت الفعلي الأثر المباشر لصدمة قطاعية على الناتج المحلي الموريتاني. يختار المستخدم القطاع المتأثر وشدة الصدمة وقطاعاً واحداً أو أكثر لتعبئتها لتعويض الخسارة.')}</p><p>{c('La plateforme recalcule immédiatement le PIB simulé, la perte directe, la croissance comptable requise dans les secteurs cibles et leur position par rapport à leurs performances historiques.','تعيد المنصة فوراً حساب الناتج المحاكى والخسارة المباشرة والنمو المحاسبي المطلوب في القطاعات المستهدفة وموقعها مقارنة بأدائها التاريخي.')}</p><p>{c('Chaque scénario transforme les séries des comptes nationaux en un récit visuel de vulnérabilité, de résilience et d’arbitrage économique accessible aux décideurs non spécialistes.','يحوّل كل سيناريو سلاسل الحسابات الوطنية إلى سرد بصري للهشاشة والمرونة والمفاضلة الاقتصادية يمكن لصناع القرار غير المتخصصين فهمه.')}</p><WarningBanner title={c('Limite méthodologique','قيد منهجي')}>{c('Cette simulation représente une analyse comptable directe. Elle ne mesure pas automatiquement les effets indirects sur l’emploi, les recettes publiques, les exportations, les fournisseurs, les prix ou la consommation des ménages.','تمثل هذه المحاكاة تحليلاً محاسبياً مباشراً. ولا تقيس تلقائياً الآثار غير المباشرة على التشغيل أو الإيرادات العامة أو الصادرات أو الموردين أو الأسعار أو استهلاك الأسر.')}</WarningBanner></div></details>
 </PageContainer>
}
