import { useEffect, useMemo, useRef, useState } from 'react'
import { Activity, ArrowDown, Gauge, Play, ShieldCheck, TriangleAlert } from 'lucide-react'
import { GdpCompositionChart } from '../components/charts/GdpCompositionChart'
import { BeforeAfterImpactChart } from '../components/charts/BeforeAfterImpactChart'
import { ResponseTimeline } from '../components/recommendations/ResponseTimeline'
import { ScenarioForm } from '../components/simulation/ScenarioForm'
import { Badge, CurrentPriceWarning, Metadata, NumberValue, useCopy } from '../components/DataDisplay'
import { LanguageSwitcher } from '../components/LanguageSwitcher'
import { KpiCard, PageContainer, PageHeader, Panel, StatePanel, WarningBanner } from '../components/Page'
import { useLanguage } from '../contexts/LanguageContext'
import { generateRecommendations } from '../services/recommendations'
import { loadDependency, loadImpactPreview, loadSimulationPageData, simulateSingle, type CompositionRow, type DependencyHistory, type SingleSimulation } from '../services/stressTest'
import type { Indicator, RecommendationResponse } from '../types/economic'

type Preview={sectorValue:number|null;baselineGdp:number|null}
const presets=[
  {code:'extractive_activities',shock:100,fr:'Arrêt extractif',ar:'توقف الاستخراج'},
  {code:'fishing',shock:50,fr:'Pêche −50 %',ar:'الصيد −50٪'},
  {code:'construction_public_works',shock:30,fr:'BTP −30 %',ar:'البناء −30٪'},
  {code:'commerce',shock:25,fr:'Commerce −25 %',ar:'التجارة −25٪'},
]
function standardDeviation(values:number[]){if(values.length<2)return null;const avg=values.reduce((a,b)=>a+b,0)/values.length;return Math.sqrt(values.reduce((sum,value)=>sum+(value-avg)**2,0)/values.length)}
function riskFor(impact:number|null){if(impact==null)return '—';if(impact<2)return 'low';if(impact<5)return 'moderate';if(impact<10)return 'high';return 'critical'}

export function SimulationAndReactionPage(){
  const c=useCopy();const {language}=useLanguage();const impactRef=useRef<HTMLElement>(null)
  const [sectors,setSectors]=useState<Indicator[]>([]),[years,setYears]=useState<number[]>([]),[composition,setComposition]=useState<CompositionRow[]>([])
  const [year,setYear]=useState(2024),[sectorCode,setSectorCode]=useState('extractive_activities'),[shockPercent,setShockPercent]=useState(50),[duration,setDuration]=useState('one_year')
  const [preview,setPreview]=useState<Preview>({sectorValue:null,baselineGdp:null}),[previewLoading,setPreviewLoading]=useState(false)
  const [result,setResult]=useState<SingleSimulation|null>(null),[dependency,setDependency]=useState<DependencyHistory|null>(null),[reaction,setReaction]=useState<RecommendationResponse|null>(null)
  const [loading,setLoading]=useState(true),[simulating,setSimulating]=useState(false),[error,setError]=useState(''),[offline,setOffline]=useState(false)
  useEffect(()=>{let active=true;loadSimulationPageData().then(data=>{if(!active)return;setSectors(data.sectors);setYears(data.years);setComposition(data.composition);if(data.years.length)setYear(data.years.at(-1) as number)}).catch(reason=>{if(active){setError(reason instanceof Error?reason.message:String(reason));setOffline(true)}}).finally(()=>active&&setLoading(false));return()=>{active=false}},[])
  useEffect(()=>{if(!sectorCode||!year)return;let active=true;setPreviewLoading(true);const timer=window.setTimeout(()=>loadImpactPreview(sectorCode,year).then(value=>active&&setPreview(value)).catch(()=>active&&setPreview({sectorValue:null,baselineGdp:null})).finally(()=>active&&setPreviewLoading(false)),300);return()=>{active=false;window.clearTimeout(timer)}},[sectorCode,year])
  const execute=async(scenario={year,sectorCode,shockPercent,duration})=>{setSimulating(true);setError('');setOffline(false);try{const simulation=await simulateSingle(scenario.year,scenario.sectorCode,scenario.shockPercent);setResult(simulation);setPreview({sectorValue:simulation.sector_value,baselineGdp:simulation.baseline_activity_gdp});const [history,plan]=await Promise.all([loadDependency(scenario.sectorCode),generateRecommendations(scenario.year,scenario.sectorCode,scenario.shockPercent,scenario.duration)]);setDependency(history);setReaction(plan);window.setTimeout(()=>impactRef.current?.scrollIntoView?.({behavior:'smooth',block:'start'}),80)}catch(reason){const apiError=reason as {response?:{data?:{error?:Record<string,string>}}};setError(apiError.response?.data?.error?.[language==='ar'?'message_ar':'message_fr']??(reason instanceof Error?reason.message:String(reason)));setOffline(!apiError.response)}finally{setSimulating(false)}}
  const reset=()=>{setYear(years.at(-1)??2024);setSectorCode('extractive_activities');setShockPercent(50);setDuration('one_year');setResult(null);setDependency(null);setReaction(null);setError('')}
  const demo=async()=>{const scenario={year:2024,sectorCode:'extractive_activities',shockPercent:100,duration:'one_year'};setYear(2024);setSectorCode(scenario.sectorCode);setShockPercent(100);setDuration('one_year');await execute(scenario)}
  const selectPreset=(code:string,shock:number)=>{setYear(2024);setSectorCode(code);setShockPercent(shock);setResult(null);setReaction(null)}
  const selected=sectors.find(item=>item.code===sectorCode);const rate=shockPercent/100
  const directLoss=preview.sectorValue==null?null:preview.sectorValue*rate;const simulatedGdp=preview.baselineGdp==null||directLoss==null?null:preview.baselineGdp-directLoss;const impact=preview.baselineGdp&&directLoss!=null?directLoss/preview.baselineGdp*100:null
  const shownImpact=result?.direct_gdp_impact_pct??impact;const shownLoss=result?.direct_loss??directLoss;const shownGdp=result?.simulated_gdp??simulatedGdp;const shownRisk=reaction?.risk_level??riskFor(shownImpact)
  const shareVolatility=useMemo(()=>standardDeviation(dependency?.points.map(point=>point.dependency_pct)??[]),[dependency]);const confidence=dependency?(dependency.points.length>=24?'high':dependency.points.length>=16?'moderate':'low'):'—'
  if(loading)return <PageContainer><div className="animate-pulse space-y-6" role="status" aria-label={c('Chargement','تحميل')}><div className="h-10 w-2/3 rounded bg-slate-200"/><div className="grid gap-5 lg:grid-cols-3"><div className="h-96 rounded-2xl bg-slate-200"/><div className="h-96 rounded-2xl bg-slate-200"/><div className="h-96 rounded-2xl bg-slate-200"/></div></div></PageContainer>
  if(error&&!composition.length)return <PageContainer><StatePanel state="error" title={offline?c('Backend indisponible','الخادم غير متاح'):c('Erreur API','خطأ في الواجهة البرمجية')} description={error}/></PageContainer>
  if(!composition.length||!sectors.length)return <PageContainer><StatePanel state="empty" title={c('Données indisponibles','البيانات غير متاحة')} description={c('Importez les comptes nationaux avant de simuler.','استورد الحسابات الوطنية قبل المحاكاة.')}/></PageContainer>
  return <PageContainer><PageHeader eyebrow={c('Economic Scenario Cockpit','قمرة السيناريو الاقتصادي')} title={c('Et si un secteur s’arrêtait demain ?','ماذا لو توقف أحد القطاعات غداً؟')} description={c('Un scénario lisible, un impact comptable immédiat et un plan de résilience fondé sur les données disponibles.','سيناريو واضح وأثر محاسبي فوري وخطة مرونة مبنية على البيانات المتاحة.')} actions={<div className="flex flex-wrap items-center gap-3"><button type="button" onClick={demo} disabled={simulating} className="inline-flex items-center gap-2 rounded-2xl bg-gold-400 px-4 py-3 font-black text-navy-950 shadow-md transition hover:-translate-y-0.5 focus:outline-none focus:ring-2 focus:ring-gold-600 motion-reduce:transform-none"><Play size={18}/>{c('Lancer la démonstration','بدء العرض التجريبي')}</button><LanguageSwitcher/></div>}/>
    <div className="mt-6"><CurrentPriceWarning/></div>{offline&&<div className="mt-4"><WarningBanner title={c('Mode hors ligne','وضع دون اتصال')}>{c('Le backend ne répond pas. Vérifiez sa connexion puis réessayez.','الخادم لا يستجيب. تحقق من الاتصال ثم أعد المحاولة.')}</WarningBanner></div>}
    <section data-testid="cockpit-grid" className="mt-6 grid items-start gap-5 xl:grid-cols-[minmax(280px,0.85fr)_minmax(430px,1.5fr)_minmax(280px,0.85fr)]">
      <Panel title={c('Construire le scénario','بناء السيناريو')}><div className="mb-5 flex flex-wrap gap-2">{presets.map(item=><button type="button" key={item.code} onClick={()=>selectPreset(item.code,item.shock)} className="rounded-full border border-gold-200 bg-gold-50 px-3 py-1.5 text-xs font-bold text-navy-900 hover:bg-gold-100 focus:outline-none focus:ring-2 focus:ring-gold-400">{c(item.fr,item.ar)}</button>)}</div><ScenarioForm years={years} sectors={sectors} year={year} sectorCode={sectorCode} shockPercent={shockPercent} duration={duration} busy={simulating} onYear={setYear} onSector={setSectorCode} onShock={setShockPercent} onDuration={setDuration} onSimulate={()=>void execute()} onReset={reset}/></Panel>
      <Panel title={c('Composition historique — 100 %','التركيب التاريخي — 100٪')} subtitle={c('Cliquez sur une zone pour sélectionner son secteur.','انقر على مساحة لاختيار قطاعها.')}><GdpCompositionChart data={composition} selectedSector={sectorCode} selectedYear={year} onSelect={setSectorCode}/><div className="mt-3 flex flex-wrap gap-2">{['primary_sector','extractive_activities','manufacturing','construction_public_works','tertiary_sector'].map(code=><button type="button" data-testid={`composition-select-${code}`} onClick={()=>setSectorCode(code)} className={`rounded-full px-3 py-1 text-xs ${sectorCode===code?'bg-navy-900 text-white':'bg-slate-100'}`} key={code}>{c(sectors.find(item=>item.code===code)?.name_fr??code,sectors.find(item=>item.code===code)?.name_ar??code)}</button>)}</div></Panel>
      <section ref={impactRef} aria-labelledby="impact-heading" className="scroll-mt-24 rounded-2xl border border-orange-200 bg-gradient-to-br from-white to-orange-50 p-5 shadow-lg"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-orange-700">{c('Impact direct','الأثر المباشر')}</p><h2 id="impact-heading" className="mt-2 text-5xl font-black tabular-nums text-navy-950">{shownImpact==null?'—':`${shownImpact.toFixed(2)}%`}</h2></div><span className="grid h-14 w-14 place-items-center rounded-2xl bg-orange-100 text-orange-700"><ArrowDown size={28}/></span></div><p className="mt-3 text-sm text-slate-600">{previewLoading?c('Actualisation…','جارٍ التحديث…'):c('Aperçu réactif; confirmé par le backend après simulation.','معاينة تفاعلية؛ يؤكدها الخادم بعد المحاكاة.')}</p><div className="mt-5 grid gap-3"><div className="rounded-2xl bg-navy-950 p-4 text-white"><p className="text-xs text-slate-300">{c('Perte directe','الخسارة المباشرة')}</p><p className="mt-1 text-2xl font-black tabular-nums"><NumberValue value={shownLoss}/> <span className="text-xs font-normal">Millions MRU</span></p></div><div className="rounded-2xl border bg-white p-4"><p className="text-xs text-slate-500">{c('PIB simulé','الناتج المحاكى')}</p><p className="mt-1 text-2xl font-black tabular-nums text-navy-950"><NumberValue value={shownGdp}/></p></div><div className="flex items-center justify-between rounded-2xl border bg-white p-4"><span className="inline-flex items-center gap-2 font-bold"><TriangleAlert size={18}/>{c('Risque','المخاطر')}</span><Badge tone={shownRisk==='critical'?'danger':shownRisk==='high'?'warning':shownRisk==='low'?'good':'neutral'}>{shownRisk}</Badge></div></div><div className="mt-5 grid grid-cols-2 gap-3"><KpiCard label={c('Valeur secteur','قيمة القطاع')} value={preview.sectorValue?.toLocaleString()??'—'}/><KpiCard label={c('Part du PIB','حصة الناتج')} value={preview.sectorValue!=null&&preview.baselineGdp?`${(preview.sectorValue/preview.baselineGdp*100).toFixed(2)}%`:'—'}/><KpiCard label={c('Volatilité','التقلب')} value={shareVolatility==null?'—':`${shareVolatility.toFixed(2)} pts`}/><KpiCard label={c('Confiance','الثقة')} value={confidence}/></div></section>
    </section>
    {error&&<div className="mt-5"><WarningBanner title={c('Simulation impossible','تعذر إجراء المحاكاة')}>{error}</WarningBanner></div>}
    <section className="mt-6 grid gap-5 lg:grid-cols-[1.3fr_0.7fr]"><Panel title={c('PIB absolu avant / après','الناتج المطلق قبل / بعد')} subtitle={c('Millions de MRU — la perte est affichée en orange, sans normalisation.','ملايين الأوقية — الخسارة بالبرتقالي دون تطبيع.')}>{shownLoss!=null&&preview.baselineGdp!=null&&preview.sectorValue!=null?<BeforeAfterImpactChart baselineGdp={preview.baselineGdp} sectorValue={preview.sectorValue} directLoss={shownLoss} unit="Millions de MRU"/>:<StatePanel state="empty" title={c('Données en attente','في انتظار البيانات')} description={c('Sélectionnez un scénario disponible.','اختر سيناريو متاحاً.')}/>}</Panel><Panel title={c('Lecture rapide','قراءة سريعة')}><div className="space-y-4 text-sm leading-6"><p className="flex gap-3"><Activity className="shrink-0 text-orange-600"/><span>{c(`Une baisse de ${shockPercent}% de ${selected?.name_fr??sectorCode} réduit directement le PIB comptable du montant simulé.`,`انخفاض ${selected?.name_ar??sectorCode} بنسبة ${shockPercent}٪ يخفض الناتج المحاسبي مباشرة بالمبلغ المحاكى.`)}</span></p><p className="flex gap-3"><Gauge className="shrink-0 text-gold-600"/><span>{c('Le graphique historique décrit la composition relative, pas la perte absolue.','الرسم التاريخي يصف التركيب النسبي وليس الخسارة المطلقة.')}</span></p><p className="flex gap-3"><ShieldCheck className="shrink-0 text-mauritania-700"/><span>{c('Les réactions sont des options déterministes, jamais des décisions officielles.','الاستجابات خيارات حتمية وليست قرارات رسمية.')}</span></p></div></Panel></section>
    <section className="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-6"><p className="text-xs font-black uppercase tracking-widest text-mauritania-700">{c('Plan de réponse et de résilience','خطة الاستجابة والمرونة')}</p><h2 className="mt-2 text-3xl font-black text-navy-950">{c('Que peut-on faire ?','ما الذي يمكن فعله؟')}</h2></div>{simulating?<StatePanel state="loading" title={c('Génération du plan','إنشاء الخطة')} description="…"/>:reaction?<><ResponseTimeline recommendations={reaction.recommendations}/><div className="mt-6"><WarningBanner title={c('Options non officielles','خيارات غير رسمية')}>{c(reaction.disclaimer_fr,reaction.disclaimer_ar)}</WarningBanner></div></>:<StatePanel state="empty" title={c('Confirmez le scénario','أكد السيناريو')} description={c('Le plan complet apparaît après avoir cliqué sur Simuler.','تظهر الخطة الكاملة بعد الضغط على محاكاة.')}/>}</section>
    <section className="mt-6 grid gap-3"><details className="rounded-2xl border bg-white p-4"><summary className="cursor-pointer font-bold">{c('Méthodologie et calcul','المنهجية والحساب')}</summary><p className="mt-3 text-sm leading-6 text-slate-600">direct_loss = sector_value × shock_rate; simulated_gdp = baseline_gdp − direct_loss; impact = direct_loss / baseline_gdp × 100.</p></details><details className="rounded-2xl border bg-white p-4"><summary className="cursor-pointer font-bold">{c('Source, données manquantes et limites','المصدر والبيانات المفقودة والحدود')}</summary><div className="mt-3 text-sm leading-6 text-slate-600"><Metadata/><p className="mt-3">{c('ANSADE/CN, prix courants. Les valeurs manquantes restent indisponibles. La simulation ne mesure pas les effets indirects, l’emploi, les finances publiques ou la causalité.','الوكالة الوطنية للإحصاء، أسعار جارية. تبقى القيم المفقودة غير متاحة. لا تقيس المحاكاة الآثار غير المباشرة أو التشغيل أو المالية العامة أو السببية.')}</p></div></details>{result&&<details className="rounded-2xl border bg-white p-4"><summary className="cursor-pointer font-bold">{c('Détails du résultat confirmé','تفاصيل النتيجة المؤكدة')}</summary><pre className="mt-3 overflow-auto rounded-xl bg-navy-950 p-4 text-xs text-white">{`sector_value=${result.sector_value}\nshock_rate=${result.shock_rate}\ndirect_loss=${result.direct_loss}\nsimulated_gdp=${result.simulated_gdp}\ndirect_impact_pct=${result.direct_gdp_impact_pct}`}</pre></details>}</section>
  </PageContainer>
}
